version: "2"
linters:
  default: all
  disable:
    - errcheck
    - goconst
    - wsl
    - varnamelen
    - cyclop
    - wrapcheck
    - testpackage
    - tagalign  # 一旦無効のまま（構造体タグの整列）
    - mnd
    - lll
    - paralleltest
    - funcorder
    - depguard
    - exhaustruct
    - nonamedreturns
    - gosec
    - prealloc  # スライスの事前割り当て（パフォーマンス最適化のため無効化）
    - noinlineerr  # インラインエラーハンドリングは一般的なGoイディオム
    - unparam  # 将来の拡張やインターフェース統一のために必要なパラメータが多数存在
    - gocognit
    - funlen
    - nestif
    - gocyclo
    - nlreturn  # 一旦無効のまま（return前の改行）
    - errchkjson
    - contextcheck
    - revive    # 一旦無効のまま（多くのルールを含む）
    - godot     # 一旦無効のまま（コメントの句点）
    - ireturn
    - gochecknoglobals
    - maintidx
    - forbidigo
    - gocritic  # 一旦無効のまま（多くのルールを含む）
    - testifylint # 一旦無効のまま（testifyライブラリ使用時のみ有用）
    - exhaustive
    - dupword
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - forcetypeassert
          - noctx
          - prealloc
          - err113
          - dupl
          - dogsled
      - path: main.go
        linters:
          - forbidigo
      - path: cmd
        linters:
          - godox
      - path: functionsigs
        linters:
          - dupl
      - path: examples/kanban/internal/handler
        linters:
          - dupl
run:
  timeout: 5m
