//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
	"time"
)

// CreateNotificationResult represents the response structure for CreateNotification
type CreateNotificationResult struct {
	ID         int        `json:"id"`
	Title      string     `json:"title"`
	Body       string     `json:"body"`
	Important  *bool      `json:"important"`
	Cancelable *bool      `json:"cancelable"`
	IconUrl    *string    `json:"icon_url"`
	ExpiresAt  *time.Time `json:"expires_at"`
	CreatedAt  *time.Time `json:"created_at"`
}

// CreateNotificationExplangExpressions stores explang steps aligned with expression indexes.
var CreateNotificationExplangExpressions = []snapsqlgo.ExplangExpression{
	snapsqlgo.ExplangExpression{
		ID: "expr_001",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "title", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 38, Column: 5, Offset: 0, Length: 5}},
		},
	},
	snapsqlgo.ExplangExpression{
		ID: "expr_002",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "body", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 40, Column: 5, Offset: 0, Length: 4}},
		},
	},
	snapsqlgo.ExplangExpression{
		ID: "expr_003",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "important", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 42, Column: 5, Offset: 0, Length: 9}},
		},
	},
	snapsqlgo.ExplangExpression{
		ID: "expr_004",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "cancelable", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 44, Column: 5, Offset: 0, Length: 10}},
		},
	},
	snapsqlgo.ExplangExpression{
		ID: "expr_005",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "icon_url", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 46, Column: 5, Offset: 0, Length: 8}},
		},
	},
	snapsqlgo.ExplangExpression{
		ID: "expr_006",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "expires_at", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 48, Column: 5, Offset: 0, Length: 10}},
		},
	},
}

const createNotificationMockPath = ""

// CreateNotification 新しい通知を作成します。通知のタイトル、本文、重要度、キャンセル可能フラグ、アイコンURL、有効期限を指定できます。
func CreateNotification(ctx context.Context, executor snapsqlgo.DBExecutor, title string, body string, important bool, cancelable bool, iconUrl string, expiresAt time.Time, opts ...snapsqlgo.FuncOpt) (CreateNotificationResult, error) {
	var result CreateNotificationResult

	// Hierarchical metas (for nested aggregation code generation - placeholder)
	// Count: 0
	// Extract implicit parameters (system arguments). Build specs from explicit
	// ImplicitParams when provided by configuration; otherwise synthesize
	// minimal specs from the SQL builder's ArgumentSystemFields. This ensures
	// generated code that references systemValues always has a declaration,
	// avoiding undefined identifier errors even when the user's config omitted
	// a system section (config defaulting is handled elsewhere).
	implicitSpecs := []snapsqlgo.ImplicitParamSpec{
		{Name: "created_at", Type: "time.Time", Required: false},
		{Name: "updated_at", Type: "time.Time", Required: false},
	}
	systemValues := snapsqlgo.ExtractImplicitParams(ctx, implicitSpecs)
	_ = systemValues // avoid unused if not referenced in args

	execCtx := snapsqlgo.ExtractExecutionContext(ctx)
	rowLockMode := snapsqlgo.RowLockNone
	if execCtx != nil {
		rowLockMode = execCtx.RowLockMode()
	}
	if rowLockMode != snapsqlgo.RowLockNone {
		snapsqlgo.EnsureRowLockAllowed(snapsqlgo.QueryLogQueryTypeExec, rowLockMode)
	}
	rowLockClause := ""
	if rowLockMode != snapsqlgo.RowLockNone {
		var rowLockErr error
		// Call dialect-specific helper generated for each target dialect to avoid runtime dialect checks.
		rowLockClause, rowLockErr = snapsqlgo.BuildRowLockClausePostgres(rowLockMode)
		if rowLockErr != nil {
			// Return error in a manner appropriate for the function kind (iterator vs normal).
			// non-iterator: return the zero value result and the error
			return result, rowLockErr
		}
	}
	queryLogOptions := snapsqlgo.QueryOptionsSnapshot{
		RowLockClause: rowLockClause,
		RowLockMode:   rowLockMode,
	}

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "INSERT INTO notifications ( title, body, important, cancelable, icon_url, expires_at , created_at, updated_at) VALUES ( $1, $2, $3, $4, $5, $6 , $7, $8)\n\n RETURNING id, title, body, important, cancelable, icon_url, expires_at, created_at"
		args := make([]any, 0)
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(title))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(body))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(important))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(cancelable))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(iconUrl))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(expiresAt))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(systemValues["created_at"]))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(systemValues["updated_at"]))
		return query, args, nil
	}
	query, args, err := buildQueryAndArgs()
	if err != nil {
		return result, err
	}
	// Handle mock execution if present
	if mockExec, mockMatched, mockErr := snapsqlgo.MatchMock(ctx, "CreateNotification"); mockMatched {
		if mockErr != nil {
			return result, mockErr
		}
		if mockExec.Err != nil {
			return result, mockExec.Err
		}
		mapped, err := snapsqlgo.MapMockExecutionToStruct[CreateNotificationResult](mockExec)
		if err != nil {
			return result, fmt.Errorf("CreateNotification: failed to map mock execution: %w", err)
		}
		result = mapped
		return result, nil
	}
	// Prepare query logger
	logger := execCtx.QueryLogger()
	logger.SetQuery(query, args)
	defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
		return snapsqlgo.QueryLogMetadata{
			FuncName:   "CreateNotification",
			SourceFile: "query/CreateNotification",
			QueryType:  snapsqlgo.QueryLogQueryTypeExec,
			Options:    queryLogOptions,
		}, executor
	})
	// Execute query
	stmt, err := executor.PrepareContext(ctx, query)
	if err != nil {
		err = fmt.Errorf("CreateNotification: failed to prepare statement: %w (query: %s)", err, query)
		return result, err
	}
	defer stmt.Close()
	// Execute query and scan single row
	row := stmt.QueryRowContext(ctx, args...)
	err = row.Scan(
		&result.ID,
		&result.Title,
		&result.Body,
		&result.Important,
		&result.Cancelable,
		&result.IconUrl,
		&result.ExpiresAt,
		&result.CreatedAt,
	)
	if err != nil {
		return result, fmt.Errorf("failed to scan row: %w", err)
	}

	return result, nil
}
