//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
	"iter"
	"strings"
	"time"
)

// ListUserNotificationsResult represents the response structure for ListUserNotifications
type ListUserNotificationsResult struct {
	ID          int        `json:"id"`
	Title       string     `json:"title"`
	Body        string     `json:"body"`
	IconUrl     *string    `json:"icon_url"`
	Important   *bool      `json:"important"`
	Cancelable  *bool      `json:"cancelable"`
	ExpiresAt   *time.Time `json:"expires_at"`
	CreatedAt   *time.Time `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
	ReadAt      *time.Time `json:"read_at"`
	DeliveredAt *time.Time `json:"delivered_at"`
}

// ListUserNotificationsExplangExpressions stores explang steps aligned with expression indexes.
var ListUserNotificationsExplangExpressions = []snapsqlgo.ExplangExpression{
	snapsqlgo.ExplangExpression{
		ID: "expr_001",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "user_id", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 48, Column: 19, Offset: 0, Length: 7}},
		},
	},
	snapsqlgo.ExplangExpression{
		ID: "expr_002",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "unread_only", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 50, Column: 5, Offset: 0, Length: 11}},
		},
	},
	snapsqlgo.ExplangExpression{
		ID: "expr_003",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "has_since", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 56, Column: 5, Offset: 0, Length: 9}},
		},
	},
	snapsqlgo.ExplangExpression{
		ID: "expr_004",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "since", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 58, Column: 24, Offset: 0, Length: 5}},
		},
	},
}

const listUserNotificationsMockPath = ""

// ListUserNotifications ユーザーの受信箱にある通知一覧を取得します。未読/既読、重要度、有効期限でフィルタリングでき、ページネーションに対応しています。キャンセルされた通知は除外されます。
func ListUserNotifications(ctx context.Context, executor snapsqlgo.DBExecutor, userID string, unreadOnly bool, since time.Time, hasSince bool, opts ...snapsqlgo.FuncOpt) iter.Seq2[*ListUserNotificationsResult, error] {

	execCtx := snapsqlgo.ExtractExecutionContext(ctx)
	rowLockMode := snapsqlgo.RowLockNone
	if execCtx != nil {
		rowLockMode = execCtx.RowLockMode()
	}
	if rowLockMode != snapsqlgo.RowLockNone {
		snapsqlgo.EnsureRowLockAllowed(snapsqlgo.QueryLogQueryTypeSelect, rowLockMode)
	}
	rowLockClause := ""
	if rowLockMode != snapsqlgo.RowLockNone {
		var rowLockErr error
		// Call dialect-specific helper generated for each target dialect to avoid runtime dialect checks.
		rowLockClause, rowLockErr = snapsqlgo.BuildRowLockClausePostgres(rowLockMode)
		if rowLockErr != nil {
			// Return error in a manner appropriate for the function kind (iterator vs normal).
			var zero *ListUserNotificationsResult
			return func(yield func(*ListUserNotificationsResult, error) bool) {
				// yield the error to the caller and exit the iterator function
				_ = yield(zero, rowLockErr)
				return
			}
		}
	}
	queryLogOptions := snapsqlgo.QueryOptionsSnapshot{
		RowLockClause: rowLockClause,
		RowLockMode:   rowLockMode,
	}

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		var builder strings.Builder
		args := make([]any, 0)
		{ // append static fragment
			_frag := "SELECT n.id, n.title, n.body, n.icon_url, n.important, n.cancelable, n.expires_at, n.created_at, n.updated_at, i.read_at, i.created_at as delivered_at FROM inbox i JOIN notifications n ON i.notification_id = n.id  WHERE i.user_id = $1"
			if builder.Len() > 0 {
				builder.WriteByte(' ')
			}
			builder.WriteString(_frag)
		}
		// Evaluate expression 0
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(userID))
		{ // append static fragment
			_frag := " "
			if builder.Len() > 0 {
				builder.WriteByte(' ')
			}
			builder.WriteString(_frag)
		}
		// IF condition: expression 1
		condValue0 := unreadOnly
		if snapsqlgo.Truthy(condValue0) {
			{ // append static fragment
				_frag := " AND i.read_at IS NULL "
				if builder.Len() > 0 {
					builder.WriteByte(' ')
				}
				builder.WriteString(_frag)
			}
		}
		{ // append static fragment
			_frag := " "
			if builder.Len() > 0 {
				builder.WriteByte(' ')
			}
			builder.WriteString(_frag)
		}
		// IF condition: expression 2
		condValue1 := hasSince
		if snapsqlgo.Truthy(condValue1) {
			{ // append static fragment
				_frag := " AND i.updated_at > $2"
				if builder.Len() > 0 {
					builder.WriteByte(' ')
				}
				builder.WriteString(_frag)
			}
			// Evaluate expression 3
			args = append(args, snapsqlgo.NormalizeNullableTimestamp(since))
			{ // append static fragment
				_frag := " "
				if builder.Len() > 0 {
					builder.WriteByte(' ')
				}
				builder.WriteString(_frag)
			}
		}
		{ // append static fragment
			_frag := " AND n.canceled_at IS NULL AND (n.expires_at IS NULL OR n.expires_at > NOW()) ORDER BY i.updated_at DESC "
			if builder.Len() > 0 {
				builder.WriteByte(' ')
			}
			builder.WriteString(_frag)
		}

		query := strings.TrimSpace(builder.String())
		return query, args, nil
	}
	return func(yield func(*ListUserNotificationsResult, error) bool) {
		query, args, err := buildQueryAndArgs()
		if err != nil {
			_ = yield(nil, err)
			return
		}
		if queryLogOptions.RowLockClause != "" {
			query += queryLogOptions.RowLockClause
		}
		// Handle mock execution if present
		if mockExec, mockMatched, mockErr := snapsqlgo.MatchMock(ctx, "ListUserNotifications"); mockMatched {
			if mockErr != nil {
				_ = yield(nil, mockErr)
				return
			}
			if mockExec.Err != nil {
				_ = yield(nil, mockExec.Err)
				return
			}

			mapped, err := snapsqlgo.MapMockExecutionToSlice[ListUserNotificationsResult](mockExec)
			if err != nil {
				_ = yield(nil, fmt.Errorf("ListUserNotifications: failed to map mock execution: %w", err))
				return
			}

			for i := range mapped {
				item := mapped[i]
				if !yield(&item, nil) {
					return
				}
			}

			return
		}
		// Prepare query logger
		logger := execCtx.QueryLogger()
		logger.SetQuery(query, args)
		defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
			return snapsqlgo.QueryLogMetadata{
				FuncName:   "ListUserNotifications",
				SourceFile: "query/ListUserNotifications",
				QueryType:  snapsqlgo.QueryLogQueryTypeSelect,
				Options:    queryLogOptions,
			}, executor
		})
		stmt, err := executor.PrepareContext(ctx, query)
		if err != nil {
			err = fmt.Errorf("ListUserNotifications: failed to prepare statement: %w (query: %s)", err, query)
			_ = yield(nil, err)
			return
		}
		defer stmt.Close()

		rows, err := stmt.QueryContext(ctx, args...)
		if err != nil {
			err = fmt.Errorf("ListUserNotifications: failed to execute query: %w", err)
			_ = yield(nil, err)
			return
		}
		defer rows.Close()

		for rows.Next() {
			item := new(ListUserNotificationsResult)
			if err := rows.Scan(
				&item.ID,
				&item.Title,
				&item.Body,
				&item.IconUrl,
				&item.Important,
				&item.Cancelable,
				&item.ExpiresAt,
				&item.CreatedAt,
				&item.UpdatedAt,
				&item.ReadAt,
				&item.DeliveredAt,
			); err != nil {
				err = fmt.Errorf("ListUserNotifications: failed to scan row: %w", err)
				_ = yield(nil, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}

		if err := rows.Err(); err != nil {
			err = fmt.Errorf("ListUserNotifications: error iterating rows: %w", err)
			_ = yield(nil, err)
			return
		}
	}
}
