//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"github.com/shibukawa/snapsql"

	"github.com/google/cel-go/cel"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
)

// UnreadNotificationForUsersResult represents the response structure for UnreadNotificationForUsers
type UnreadNotificationForUsersResult struct {
	AffectedRows int `json:"affected_rows"`
}

// UnreadNotificationForUsers specific CEL programs and mock path
var (
	unreadNotificationForUsersPrograms []cel.Program
)

const unreadNotificationForUsersMockPath = ""

func init() {

	// CEL environments based on intermediate format
	celEnvironments := make([]*cel.Env, 1)
	// Environment 0 (container: root)
	{
		// Build CEL env options
		opts := []cel.EnvOption{
			cel.Container("root"),
		}
		opts = append(opts, cel.Variable("notification_id", cel.IntType))
		opts = append(opts, cel.Variable("notification_id", cel.IntType))
		opts = append(opts,
			cel.HomogeneousAggregateLiterals(),
			cel.EagerlyValidateDeclarations(true),
			snapsqlgo.DecimalLibrary,
		)
		env0, err := cel.NewEnv(opts...)
		if err != nil {
			panic(fmt.Sprintf("failed to create UnreadNotificationForUsers CEL environment 0: %v", err))
		}
		celEnvironments[0] = env0
	}

	// Create programs for each expression using the corresponding environment
	unreadNotificationForUsersPrograms = make([]cel.Program, 1)
	// expr_001: "notification_id" using environment 0
	{
		ast, issues := celEnvironments[0].Compile("notification_id")
		if issues != nil && issues.Err() != nil {
			panic(fmt.Sprintf("failed to compile CEL expression %q: %v", "notification_id", issues.Err()))
		}
		program, err := celEnvironments[0].Program(ast)
		if err != nil {
			panic(fmt.Sprintf("failed to create CEL program for %q: %v", "notification_id", err))
		}
		unreadNotificationForUsersPrograms[0] = program
	}
}

// UnreadNotificationForUsers 通知が更新された際に、その通知を持つすべてのユーザーの既読状態をクリアします。
func UnreadNotificationForUsers(ctx context.Context, executor snapsqlgo.DBExecutor, notificationID int, opts ...snapsqlgo.FuncOpt) (any, error) {
	var result any

	// Hierarchical metas (for nested aggregation code generation - placeholder)
	// Count: 0

	execCtx := snapsqlgo.ExtractExecutionContext(ctx)
	rowLockMode := snapsqlgo.RowLockNone
	if execCtx != nil {
		rowLockMode = execCtx.RowLockMode()
	}
	if rowLockMode != snapsqlgo.RowLockNone {
		snapsqlgo.EnsureRowLockAllowed(snapsqlgo.QueryLogQueryTypeExec, rowLockMode)
	}
	rowLockClause := ""
	if rowLockMode != snapsqlgo.RowLockNone {
		var rowLockErr error
		// Call dialect-specific helper generated for each target dialect to avoid runtime dialect checks.
		rowLockClause, rowLockErr = snapsqlgo.BuildRowLockClausePostgres(rowLockMode)
		if rowLockErr != nil {
			// Return error in a manner appropriate for the function kind (iterator vs normal).
			// non-iterator: return the zero value result and the error
			return result, rowLockErr
		}
	}
	queryLogOptions := snapsqlgo.QueryOptionsSnapshot{
		RowLockClause: rowLockClause,
		RowLockMode:   rowLockMode,
	}
	var whereMeta *snapsqlgo.WhereClauseMeta
	whereMeta = &snapsqlgo.WhereClauseMeta{
		Status:  snapsqlgo.WhereClauseStatusExists,
		RawText: "WHERE",
	}

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "UPDATE inbox SET read_at = NULL, updated_at = NOW()  WHERE notification_id = $1"
		args := make([]any, 0)
		paramMap := map[string]any{
			"notification_id": notificationID,
		}

		evalRes0, _, err := unreadNotificationForUsersPrograms[0].Eval(paramMap)
		if err != nil {
			return "", nil, fmt.Errorf("UnreadNotificationForUsers: failed to evaluate expression: %w", err)
		}
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(evalRes0))
		return query, args, nil
	}
	query, args, err := buildQueryAndArgs()
	if err != nil {
		return nil, err
	}
	// Enforce WHERE clause guard when mutations are generated
	if err := snapsqlgo.EnforceNonEmptyWhereClause(ctx, "UnreadNotificationForUsers", snapsqlgo.MutationUpdate, whereMeta, query); err != nil {
		return nil, err
	}
	// Handle mock execution if present
	if mockExec, mockMatched, mockErr := snapsqlgo.MatchMock(ctx, "UnreadNotificationForUsers"); mockMatched {
		if mockErr != nil {
			return nil, mockErr
		}
		if mockExec.Err != nil {
			return nil, mockExec.Err
		}
		mockResult := mockExec.SQLResult()
		if mockResult != nil {
			result = mockResult
			return result, nil
		}
		if len(mockExec.ExpectedRows()) > 0 {
			mapped, err := snapsqlgo.MapMockExecutionToStruct[any](mockExec)
			if err != nil {
				return nil, fmt.Errorf("UnreadNotificationForUsers: failed to map mock execution: %w", err)
			}
			result = mapped
		}
		return result, nil
	}
	// Prepare query logger
	logger := execCtx.QueryLogger()
	logger.SetQuery(query, args)
	defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
		return snapsqlgo.QueryLogMetadata{
			FuncName:   "UnreadNotificationForUsers",
			SourceFile: "query/UnreadNotificationForUsers",
			QueryType:  snapsqlgo.QueryLogQueryTypeExec,
			Options:    queryLogOptions,
		}, executor
	})
	// Execute query
	stmt, err := executor.PrepareContext(ctx, query)
	if err != nil {
		err = fmt.Errorf("UnreadNotificationForUsers: failed to prepare statement: %w (query: %s)", err, query)
		return nil, err
	}
	defer stmt.Close()
	// Execute query (no result expected)
	_, err = stmt.ExecContext(ctx, args...)
	if err != nil {
		return nil, fmt.Errorf("UnreadNotificationForUsers: failed to execute statement: %w", err)
	}

	return result, nil
}
