//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
)

// UnreadNotificationForUsersResult represents the response structure for UnreadNotificationForUsers
type UnreadNotificationForUsersResult struct {
	AffectedRows int `json:"affected_rows"`
}

// UnreadNotificationForUsersExplangExpressions stores explang steps aligned with expression indexes.
var UnreadNotificationForUsersExplangExpressions = []snapsqlgo.ExplangExpression{
	snapsqlgo.ExplangExpression{
		ID: "expr_001",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "notification_id", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 23, Column: 25, Offset: 0, Length: 15}},
		},
	},
}

const unreadNotificationForUsersMockPath = ""

// UnreadNotificationForUsers 通知が更新された際に、その通知を持つすべてのユーザーの既読状態をクリアします。
func UnreadNotificationForUsers(ctx context.Context, executor snapsqlgo.DBExecutor, notificationID int, opts ...snapsqlgo.FuncOpt) (sql.Result, error) {
	var result sql.Result

	// Hierarchical metas (for nested aggregation code generation - placeholder)
	// Count: 0

	execCtx := snapsqlgo.ExtractExecutionContext(ctx)
	rowLockMode := snapsqlgo.RowLockNone
	if execCtx != nil {
		rowLockMode = execCtx.RowLockMode()
	}
	if rowLockMode != snapsqlgo.RowLockNone {
		snapsqlgo.EnsureRowLockAllowed(snapsqlgo.QueryLogQueryTypeExec, rowLockMode)
	}
	rowLockClause := ""
	if rowLockMode != snapsqlgo.RowLockNone {
		var rowLockErr error
		// Call dialect-specific helper generated for each target dialect to avoid runtime dialect checks.
		rowLockClause, rowLockErr = snapsqlgo.BuildRowLockClausePostgres(rowLockMode)
		if rowLockErr != nil {
			// Return error in a manner appropriate for the function kind (iterator vs normal).
			// non-iterator: return the zero value result and the error
			return result, rowLockErr
		}
	}
	queryLogOptions := snapsqlgo.QueryOptionsSnapshot{
		RowLockClause: rowLockClause,
		RowLockMode:   rowLockMode,
	}
	var whereMeta *snapsqlgo.WhereClauseMeta
	whereMeta = &snapsqlgo.WhereClauseMeta{
		Status:  snapsqlgo.WhereClauseStatusExists,
		RawText: "WHERE",
	}

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "UPDATE inbox SET read_at = NULL, updated_at = NOW()  WHERE notification_id = $1"
		args := make([]any, 0)
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(notificationID))
		return query, args, nil
	}
	query, args, err := buildQueryAndArgs()
	if err != nil {
		return nil, err
	}
	// Enforce WHERE clause guard when mutations are generated
	if err := snapsqlgo.EnforceNonEmptyWhereClause(ctx, "UnreadNotificationForUsers", snapsqlgo.MutationUpdate, whereMeta, query); err != nil {
		return nil, err
	}
	// Handle mock execution if present
	if mockExec, mockMatched, mockErr := snapsqlgo.MatchMock(ctx, "UnreadNotificationForUsers"); mockMatched {
		if mockErr != nil {
			return nil, mockErr
		}
		if mockExec.Err != nil {
			return nil, mockExec.Err
		}
		mockResult := mockExec.SQLResult()
		if mockResult == nil {
			mockResult = snapsqlgo.NewMockResult(mockExec.Opt.RowsAffected, mockExec.Opt.LastInsertID)
		}
		if mockResult != nil {
			result = mockResult
		}
		return result, nil
	}
	// Prepare query logger
	logger := execCtx.QueryLogger()
	logger.SetQuery(query, args)
	defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
		return snapsqlgo.QueryLogMetadata{
			FuncName:   "UnreadNotificationForUsers",
			SourceFile: "query/UnreadNotificationForUsers",
			QueryType:  snapsqlgo.QueryLogQueryTypeExec,
			Options:    queryLogOptions,
		}, executor
	})
	// Execute query
	stmt, err := executor.PrepareContext(ctx, query)
	if err != nil {
		err = fmt.Errorf("UnreadNotificationForUsers: failed to prepare statement: %w (query: %s)", err, query)
		return nil, err
	}
	defer stmt.Close()
	// Execute query (no result expected)
	execResult, err := stmt.ExecContext(ctx, args...)
	if err != nil {
		return nil, fmt.Errorf("UnreadNotificationForUsers: failed to execute statement: %w", err)
	}
	result = execResult

	return result, nil
}
