# Generated by snapsql - DO NOT EDIT
# Generated at: 2025-11-20T20:47:34+09:00
# Function: comment_list_by_post
# Dialect: postgres

"""
Lists all comments for a specific post with author information, ordered by creation date.
"""

from dataclasses import dataclass, asdict
from typing import Optional, List, Any, Dict, AsyncGenerator, Union
from datetime import datetime
from decimal import Decimal
from .snapsql_runtime import (
    get_snapsql_context,
    ValidationError,
    NotFoundError,
    QueryLogMetadata,
    ROW_LOCK_NONE,
    ensure_row_lock_allowed,
    build_row_lock_clause_postgres,
)
# PostgreSQL async driver
try:
    import asyncpg
except ImportError:
    raise ImportError("asyncpg is required for PostgreSQL. Install with: pip install asyncpg")

# ============================================================================
# Response Structures
# ============================================================================

@dataclass
class CommentListByPostResultAuthor:
    """Response structure for comment_list_by_post"""
    username: str
    full_name: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization"""
        return asdict(self)

@dataclass
class CommentListByPostResult:
    """Response structure for comment_list_by_post"""
    comment_id: int
    post_id: int
    author_id: int
    content: str
    created_at: datetime
    updated_at: datetime
    author: List[CommentListByPostResultAuthor] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization"""
        return asdict(self)


# ============================================================================
# Generated Functions
# ============================================================================
async def comment_list_by_post(
    conn: asyncpg.Connection,
    post_id: int,
) -> AsyncGenerator[CommentListByPostResult, None]:
    """
    Lists all comments for a specific post with author information, ordered by creation date.
    
    Args:
        post_id: 
    
    Returns:
        Result of comment_list_by_post
    """
    # Validate required parameters
    if post_id is None:
        raise ValidationError(
            message="Required parameter 'post_id' cannot be None",
            param_name="post_id",
            func_name="comment_list_by_post"
        )
    
    # Build SQL
    sql = """SELECT c.comment_id, c.post_id, c.author_id, c.content, c.created_at, c.updated_at, u.username as author__username, u.full_name as author__full_name FROM comments c JOIN users u ON c.author_id = u.user_id WHERE c.post_id = $1 ORDER BY c.created_at ASC """
    args = [post_id]

    ctx = get_snapsql_context()
    row_lock_clause = ""
    if ctx.row_lock_mode not in (None, "", ROW_LOCK_NONE):
        ensure_row_lock_allowed("select", ctx.row_lock_mode)
        row_lock_clause = build_row_lock_clause_postgres(ctx.row_lock_mode)
        if row_lock_clause:
            sql += row_lock_clause
    logger = ctx.query_logger if ctx.enable_query_log else None
    error = None
    row_count = None
    import time
    start_time = time.time()
    try:
        # Execute query for hierarchical aggregation
        # This aggregates child records into parent objects

        rows = await conn.fetch(sql, *args)

        # Process rows for hierarchical aggregation
        current_parent = None
        current_parent_key = None

        for row in rows:
            row_dict = dict(row)
            
            # Extract parent key
            parent_key = row_dict.get('comment_id')
            
            # Check if we have a new parent
            if parent_key != current_parent_key:
                # Yield previous parent if exists
                if current_parent is not None:
                    yield current_parent
                
                # Create new parent object
                current_parent = CommentListByPostResult(
                    comment_id=row_dict.get('comment_id'),
                    post_id=row_dict.get('post_id'),
                    author_id=row_dict.get('author_id'),
                    content=row_dict.get('content'),
                    created_at=row_dict.get('created_at'),
                    updated_at=row_dict.get('updated_at'),
                    author=[]
                )
                current_parent_key = parent_key
            
            # Add child objects if present
            if any([row_dict.get('author__username'), row_dict.get('author__full_name')]):
                child_obj = CommentListByPostResultAuthor(
                    username=row_dict.get('author__username'),
                    full_name=row_dict.get('author__full_name')
                )
                current_parent.author.append(child_obj)

        # Yield last parent if exists
        if current_parent is not None:
            yield current_parent
    except Exception as err:
        error = err
        raise
    finally:
        if logger:
            duration_ms = (time.time() - start_time) * 1000
            metadata = QueryLogMetadata(
                func_name="comment_list_by_post",
                source_file="comment_list_by_post",
                dialect="postgres",
                query_type="select"
            )
            await logger.write(metadata, duration_ms, row_count, error)
