# Generated by snapsql - DO NOT EDIT
# Generated at: 2025-11-20T20:47:34+09:00
# Function: post_get
# Dialect: postgres

"""
Retrieves a single post by ID with author information (hierarchical response).
"""

from dataclasses import dataclass, asdict
from typing import Optional, List, Any, Dict, AsyncGenerator, Union
from datetime import datetime
from decimal import Decimal
from .snapsql_runtime import (
    get_snapsql_context,
    ValidationError,
    QueryLogMetadata,
    ROW_LOCK_NONE,
    ensure_row_lock_allowed,
    build_row_lock_clause_postgres,
)
# PostgreSQL async driver
try:
    import asyncpg
except ImportError:
    raise ImportError("asyncpg is required for PostgreSQL. Install with: pip install asyncpg")

# ============================================================================
# Response Structures
# ============================================================================

@dataclass
class PostGetResultAuthor:
    """Response structure for post_get"""
    username: str
    full_name: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization"""
        return asdict(self)

@dataclass
class PostGetResult:
    """Response structure for post_get"""
    post_id: int
    title: str
    content: str
    author_id: int
    published: bool
    view_count: int
    created_at: datetime
    updated_at: datetime
    author: List[PostGetResultAuthor] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization"""
        return asdict(self)


# ============================================================================
# Generated Functions
# ============================================================================
async def post_get(
    conn: asyncpg.Connection,
    post_id: int,
) -> PostGetResult:
    """
    Retrieves a single post by ID with author information (hierarchical response).
    
    Args:
        post_id: 
    
    Returns:
        Result of post_get
    """
    # Validate required parameters
    if post_id is None:
        raise ValidationError(
            message="Required parameter 'post_id' cannot be None",
            param_name="post_id",
            func_name="post_get"
        )
    
    # Build SQL
    sql = """SELECT p.post_id, p.title, p.content, p.author_id, p.published, p.view_count, p.created_at, p.updated_at, u.username as author__username, u.full_name as author__full_name FROM posts p JOIN users u ON p.author_id = u.user_id WHERE p.post_id = $1 """
    args = [post_id]

    ctx = get_snapsql_context()
    row_lock_clause = ""
    if ctx.row_lock_mode not in (None, "", ROW_LOCK_NONE):
        ensure_row_lock_allowed("select", ctx.row_lock_mode)
        row_lock_clause = build_row_lock_clause_postgres(ctx.row_lock_mode)
        if row_lock_clause:
            sql += row_lock_clause
    logger = ctx.query_logger if ctx.enable_query_log else None
    error = None
    row_count = None
    import time
    start_time = time.time()
    try:
        # Execute query for hierarchical aggregation (one affinity)
        # This aggregates multiple rows into a single parent object with child lists

        rows = await conn.fetch(sql, *args)

        if not rows:
            raise NotFoundError(
                message="Record not found",
                func_name="post_get",
                query=sql
            )

        # Process rows for hierarchical aggregation
        result = None

        for row in rows:
            row_dict = dict(row)
            
            # Create parent object on first row
            if result is None:
                result = PostGetResult(
                    post_id=row_dict.get('post_id'),
                    title=row_dict.get('title'),
                    content=row_dict.get('content'),
                    author_id=row_dict.get('author_id'),
                    published=row_dict.get('published'),
                    view_count=row_dict.get('view_count'),
                    created_at=row_dict.get('created_at'),
                    updated_at=row_dict.get('updated_at'),
                    author=[]
                )
            
            # Add child objects if present
            if any([row_dict.get('author__username'), row_dict.get('author__full_name')]):
                child_obj = PostGetResultAuthor(
                    username=row_dict.get('author__username'),
                    full_name=row_dict.get('author__full_name')
                )
                result.author.append(child_obj)

        return result
    except Exception as err:
        error = err
        raise
    finally:
        if logger:
            duration_ms = (time.time() - start_time) * 1000
            metadata = QueryLogMetadata(
                func_name="post_get",
                source_file="post_get",
                dialect="postgres",
                query_type="select"
            )
            await logger.write(metadata, duration_ms, row_count, error)
