//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package appsamplepg

import (
	"context"
	"fmt"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
)

// AccountGetResult represents the response structure for AccountGet
type AccountGetResult struct {
	ID     int     `json:"id"`
	Name   *string `json:"name"`
	Status *string `json:"status"`
}

// AccountGetExplangExpressions stores explang steps aligned with expression indexes.
var AccountGetExplangExpressions = []snapsqlgo.ExplangExpression{
	snapsqlgo.ExplangExpression{
		ID: "expr_001",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "account_id", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 12, Column: 12, Offset: 0, Length: 10}},
		},
	},
}

const accountGetMockPath = ""

// AccountGet - AccountGetResult Affinity
func AccountGet(ctx context.Context, executor snapsqlgo.DBExecutor, accountID int, opts ...snapsqlgo.FuncOpt) (AccountGetResult, error) {
	var result AccountGetResult

	// Hierarchical metas (for nested aggregation code generation - placeholder)
	// Count: 0

	execCtx := snapsqlgo.ExtractExecutionContext(ctx)
	rowLockMode := snapsqlgo.RowLockNone
	if execCtx != nil {
		rowLockMode = execCtx.RowLockMode()
	}
	if rowLockMode != snapsqlgo.RowLockNone {
		snapsqlgo.EnsureRowLockAllowed(snapsqlgo.QueryLogQueryTypeSelect, rowLockMode)
	}
	rowLockClause := ""
	if rowLockMode != snapsqlgo.RowLockNone {
		var rowLockErr error
		// Call dialect-specific helper generated for each target dialect to avoid runtime dialect checks.
		rowLockClause, rowLockErr = snapsqlgo.BuildRowLockClausePostgres(rowLockMode)
		if rowLockErr != nil {
			// Return error in a manner appropriate for the function kind (iterator vs normal).
			// non-iterator: return the zero value result and the error
			return result, rowLockErr
		}
	}
	queryLogOptions := snapsqlgo.QueryOptionsSnapshot{
		RowLockClause: rowLockClause,
		RowLockMode:   rowLockMode,
	}

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "SELECT id, name, status FROM accounts  WHERE id = $1 "
		args := make([]any, 0)
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(accountID))
		return query, args, nil
	}
	query, args, err := buildQueryAndArgs()
	if err != nil {
		return result, err
	}
	if queryLogOptions.RowLockClause != "" {
		query += queryLogOptions.RowLockClause
	}
	// Handle mock execution if present
	if mockExec, mockMatched, mockErr := snapsqlgo.MatchMock(ctx, "AccountGet"); mockMatched {
		if mockErr != nil {
			return result, mockErr
		}
		if mockExec.Err != nil {
			return result, mockExec.Err
		}
		mapped, err := snapsqlgo.MapMockExecutionToStruct[AccountGetResult](mockExec)
		if err != nil {
			return result, fmt.Errorf("AccountGet: failed to map mock execution: %w", err)
		}
		result = mapped
		return result, nil
	}
	// Prepare query logger
	logger := execCtx.QueryLogger()
	logger.SetQuery(query, args)
	defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
		return snapsqlgo.QueryLogMetadata{
			FuncName:   "AccountGet",
			SourceFile: "appsamplepg/AccountGet",
			QueryType:  snapsqlgo.QueryLogQueryTypeSelect,
			Options:    queryLogOptions,
		}, executor
	})
	// Execute query
	stmt, err := executor.PrepareContext(ctx, query)
	if err != nil {
		err = fmt.Errorf("AccountGet: failed to prepare statement: %w (query: %s)", err, query)
		return result, err
	}
	defer stmt.Close()
	// Execute query and scan single row
	row := stmt.QueryRowContext(ctx, args...)
	err = row.Scan(
		&result.ID,
		&result.Name,
		&result.Status,
	)
	if err != nil {
		return result, fmt.Errorf("failed to scan row: %w", err)
	}

	return result, nil
}
