//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"time"

	"github.com/google/cel-go/cel"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
)

// BoardGetResult represents the response structure for BoardGet
type BoardGetResult struct {
	ID         int        `json:"id"`
	Name       string     `json:"name"`
	Status     string     `json:"status"`
	ArchivedAt *time.Time `json:"archived_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

// BoardGet specific CEL programs and mock path
var (
	boardGetPrograms []cel.Program
)

const boardGetMockPath = ""

func init() {

	// CEL environments based on intermediate format
	celEnvironments := make([]*cel.Env, 1)
	// Environment 0 (container: root)
	{
		// Build CEL env options
		opts := []cel.EnvOption{
			cel.Container("root"),
		}
		opts = append(opts, cel.Variable("board_id", cel.IntType))
		opts = append(opts, cel.Variable("board_id", cel.IntType))
		opts = append(opts,
			cel.HomogeneousAggregateLiterals(),
			cel.EagerlyValidateDeclarations(true),
			snapsqlgo.DecimalLibrary,
		)
		env0, err := cel.NewEnv(opts...)
		if err != nil {
			panic(fmt.Sprintf("failed to create BoardGet CEL environment 0: %v", err))
		}
		celEnvironments[0] = env0
	}

	// Create programs for each expression using the corresponding environment
	boardGetPrograms = make([]cel.Program, 1)
	// expr_001: "board_id" using environment 0
	{
		ast, issues := celEnvironments[0].Compile("board_id")
		if issues != nil && issues.Err() != nil {
			panic(fmt.Sprintf("failed to compile CEL expression %q: %v", "board_id", issues.Err()))
		}
		program, err := celEnvironments[0].Program(ast)
		if err != nil {
			panic(fmt.Sprintf("failed to create CEL program for %q: %v", "board_id", err))
		}
		boardGetPrograms[0] = program
	}
}

// BoardGet Retrieves one board record for detail views. Returns an empty result if the board does not exist.
func BoardGet(ctx context.Context, executor snapsqlgo.DBExecutor, boardID int, opts ...snapsqlgo.FuncOpt) (BoardGetResult, error) {
	var result BoardGetResult

	// Hierarchical metas (for nested aggregation code generation - placeholder)
	// Count: 0

	funcConfig := snapsqlgo.GetFunctionConfig(ctx, "boardGet", "boardgetresult")
	// Check for mock mode
	if funcConfig != nil && len(funcConfig.MockDataNames) > 0 {
		mockData, err := snapsqlgo.GetMockDataFromFiles(boardGetMockPath, funcConfig.MockDataNames)
		if err != nil {
			return result, fmt.Errorf("BoardGet: failed to get mock data: %w", err)
		}

		result, err = snapsqlgo.MapMockDataToStruct[BoardGetResult](mockData)
		if err != nil {
			return result, fmt.Errorf("BoardGet: failed to map mock data to BoardGetResult struct: %w", err)
		}

		return result, nil
	}
	logger := snapsqlgo.QueryLoggerFromContext(ctx)
	defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
		return snapsqlgo.QueryLogMetadata{
			FuncName:   "BoardGet",
			SourceFile: "query/BoardGet",
			Dialect:    "sqlite",
			QueryType:  snapsqlgo.QueryLogQueryTypeSelect,
		}, executor
	})

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "SELECT id, name, status, archived_at, created_at, updated_at FROM boards  WHERE id = $1 "
		args := make([]any, 0)
		paramMap := map[string]any{
			"board_id": boardID,
		}

		evalRes0, _, err := boardGetPrograms[0].Eval(paramMap)
		if err != nil {
			return "", nil, fmt.Errorf("BoardGet: failed to evaluate expression: %w", err)
		}
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(evalRes0))
		return query, args, nil
	}
	query, args, err := buildQueryAndArgs()
	if err != nil {
		logger.SetErr(err)
		return result, err
	}
	logger.SetQuery(query, args)
	// Execute query
	stmt, err := executor.PrepareContext(ctx, query)
	if err != nil {
		err = fmt.Errorf("BoardGet: failed to prepare statement: %w (query: %s)", err, query)
		logger.SetErr(err)
		return result, err
	}
	defer stmt.Close()
	// Execute query and scan single row
	row := stmt.QueryRowContext(ctx, args...)
	err = row.Scan(
		&result.ID,
		&result.Name,
		&result.Status,
		&result.ArchivedAt,
		&result.CreatedAt,
		&result.UpdatedAt,
	)
	if err != nil {
		err = fmt.Errorf("failed to scan row: %w", err)
		logger.SetErr(err)
		return result, err
	}

	return result, nil
}
