//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"iter"
	"time"

	"github.com/google/cel-go/cel"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
)

// BoardListResult represents the response structure for BoardList
type BoardListResult struct {
	ID         int        `json:"id"`
	Name       string     `json:"name"`
	Status     string     `json:"status"`
	ArchivedAt *time.Time `json:"archived_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

// BoardList specific CEL programs and mock path
var (
	boardListPrograms []cel.Program
)

const boardListMockPath = ""

func init() {

	// CEL environments based on intermediate format
	celEnvironments := make([]*cel.Env, 1)
	// Environment 0 (container: root)
	{
		// Build CEL env options
		opts := []cel.EnvOption{
			cel.Container("root"),
		}
		opts = append(opts,
			cel.HomogeneousAggregateLiterals(),
			cel.EagerlyValidateDeclarations(true),
			snapsqlgo.DecimalLibrary,
		)
		env0, err := cel.NewEnv(opts...)
		if err != nil {
			panic(fmt.Sprintf("failed to create BoardList CEL environment 0: %v", err))
		}
		celEnvironments[0] = env0
	}

	// Create programs for each expression using the corresponding environment
	boardListPrograms = make([]cel.Program, 0)
}

// BoardList Fetches every board with basic metadata, ordered by most recently created first. Used for the dashboard overview.
func BoardList(ctx context.Context, executor snapsqlgo.DBExecutor, opts ...snapsqlgo.FuncOpt) iter.Seq2[*BoardListResult, error] {

	execCtx := snapsqlgo.ExtractExecutionContext(ctx)
	rowLockMode := snapsqlgo.RowLockNone
	if execCtx != nil {
		rowLockMode = execCtx.RowLockMode()
	}
	if rowLockMode != snapsqlgo.RowLockNone {
		snapsqlgo.EnsureRowLockAllowed(snapsqlgo.QueryLogQueryTypeSelect, rowLockMode)
	}
	rowLockClause := ""
	if rowLockMode != snapsqlgo.RowLockNone {
		var rowLockErr error
		rowLockClause, rowLockErr = snapsqlgo.BuildRowLockClause("sqlite", rowLockMode)
		if rowLockErr != nil {
			panic(rowLockErr)
		}
	}
	queryLogOptions := snapsqlgo.QueryOptionsSnapshot{
		RowLockClause: rowLockClause,
		RowLockMode:   rowLockMode,
	}

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "SELECT id, name, status, archived_at, created_at, updated_at FROM boards ORDER BY created_at DESC "
		args := make([]any, 0)
		return query, args, nil
	}
	return func(yield func(*BoardListResult, error) bool) {
		logger := execCtx.QueryLogger()
		defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
			return snapsqlgo.QueryLogMetadata{
				FuncName:   "BoardList",
				SourceFile: "query/BoardList",
				Dialect:    "sqlite",
				QueryType:  snapsqlgo.QueryLogQueryTypeSelect,
				Options:    queryLogOptions,
			}, executor
		})

		query, args, err := buildQueryAndArgs()
		if err != nil {
			logger.SetErr(err)
			_ = yield(nil, err)
			return
		}
		logger.SetQuery(query, args)
		if mockExec, mockMatched, mockErr := snapsqlgo.MatchMock(ctx, "BoardList"); mockMatched {
			if mockErr != nil {
				logger.SetErr(mockErr)
				_ = yield(nil, mockErr)
				return
			}
			if mockExec.Err != nil {
				logger.SetErr(mockExec.Err)
				_ = yield(nil, mockExec.Err)
				return
			}

			mapped, err := snapsqlgo.MapMockExecutionToSlice[BoardListResult](mockExec)
			if err != nil {
				logger.SetErr(err)
				_ = yield(nil, fmt.Errorf("BoardList: failed to map mock execution: %w", err))
				return
			}

			for i := range mapped {
				item := mapped[i]
				if !yield(&item, nil) {
					return
				}
			}

			return
		}
		stmt, err := executor.PrepareContext(ctx, query)
		if err != nil {
			err = fmt.Errorf("BoardList: failed to prepare statement: %w (query: %s)", err, query)
			logger.SetErr(err)
			_ = yield(nil, err)
			return
		}
		defer stmt.Close()

		rows, err := stmt.QueryContext(ctx, args...)
		if err != nil {
			err = fmt.Errorf("BoardList: failed to execute query: %w", err)
			logger.SetErr(err)
			_ = yield(nil, err)
			return
		}
		defer rows.Close()

		for rows.Next() {
			item := new(BoardListResult)
			if err := rows.Scan(
				&item.ID,
				&item.Name,
				&item.Status,
				&item.ArchivedAt,
				&item.CreatedAt,
				&item.UpdatedAt,
			); err != nil {
				err = fmt.Errorf("BoardList: failed to scan row: %w", err)
				logger.SetErr(err)
				_ = yield(nil, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}

		if err := rows.Err(); err != nil {
			err = fmt.Errorf("BoardList: error iterating rows: %w", err)
			logger.SetErr(err)
			_ = yield(nil, err)
			return
		}
	}
}
