//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
	"iter"
	"time"
)

// BoardListResult represents the response structure for BoardList
type BoardListResult struct {
	ID         int        `json:"id"`
	Name       string     `json:"name"`
	Status     string     `json:"status"`
	ArchivedAt *time.Time `json:"archived_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

const boardListMockPath = ""

// BoardList Fetches every board with basic metadata, ordered by most recently created first. Used for the dashboard overview.
func BoardList(ctx context.Context, executor snapsqlgo.DBExecutor, opts ...snapsqlgo.FuncOpt) iter.Seq2[*BoardListResult, error] {

	execCtx := snapsqlgo.ExtractExecutionContext(ctx)
	rowLockMode := snapsqlgo.RowLockNone
	if execCtx != nil {
		rowLockMode = execCtx.RowLockMode()
	}
	if rowLockMode != snapsqlgo.RowLockNone {
		snapsqlgo.EnsureRowLockAllowed(snapsqlgo.QueryLogQueryTypeSelect, rowLockMode)
	}
	rowLockClause := ""
	if rowLockMode != snapsqlgo.RowLockNone {
		var rowLockErr error
		// Call dialect-specific helper generated for each target dialect to avoid runtime dialect checks.
		// SQLite does not support row locks. For SELECT queries we silently ignore the clause;
		// for mutation queries we treat this as an error.
		rowLockClause, _ = snapsqlgo.BuildRowLockClauseSQLite(rowLockMode)
		if rowLockErr != nil {
			// Return error in a manner appropriate for the function kind (iterator vs normal).
			var zero *BoardListResult
			return func(yield func(*BoardListResult, error) bool) {
				// yield the error to the caller and exit the iterator function
				_ = yield(zero, rowLockErr)
				return
			}
		}
	}
	queryLogOptions := snapsqlgo.QueryOptionsSnapshot{
		RowLockClause: rowLockClause,
		RowLockMode:   rowLockMode,
	}

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "SELECT id, name, status, archived_at, created_at, updated_at FROM boards ORDER BY created_at DESC "
		args := make([]any, 0)
		return query, args, nil
	}
	return func(yield func(*BoardListResult, error) bool) {
		query, args, err := buildQueryAndArgs()
		if err != nil {
			_ = yield(nil, err)
			return
		}
		// Handle mock execution if present
		if mockExec, mockMatched, mockErr := snapsqlgo.MatchMock(ctx, "BoardList"); mockMatched {
			if mockErr != nil {
				_ = yield(nil, mockErr)
				return
			}
			if mockExec.Err != nil {
				_ = yield(nil, mockExec.Err)
				return
			}

			mapped, err := snapsqlgo.MapMockExecutionToSlice[BoardListResult](mockExec)
			if err != nil {
				_ = yield(nil, fmt.Errorf("BoardList: failed to map mock execution: %w", err))
				return
			}

			for i := range mapped {
				item := mapped[i]
				if !yield(&item, nil) {
					return
				}
			}

			return
		}
		// Prepare query logger
		logger := execCtx.QueryLogger()
		logger.SetQuery(query, args)
		defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
			return snapsqlgo.QueryLogMetadata{
				FuncName:   "BoardList",
				SourceFile: "query/BoardList",
				QueryType:  snapsqlgo.QueryLogQueryTypeSelect,
				Options:    queryLogOptions,
			}, executor
		})
		stmt, err := executor.PrepareContext(ctx, query)
		if err != nil {
			err = fmt.Errorf("BoardList: failed to prepare statement: %w (query: %s)", err, query)
			_ = yield(nil, err)
			return
		}
		defer stmt.Close()

		rows, err := stmt.QueryContext(ctx, args...)
		if err != nil {
			err = fmt.Errorf("BoardList: failed to execute query: %w", err)
			_ = yield(nil, err)
			return
		}
		defer rows.Close()

		for rows.Next() {
			item := new(BoardListResult)
			if err := rows.Scan(
				&item.ID,
				&item.Name,
				&item.Status,
				&item.ArchivedAt,
				&item.CreatedAt,
				&item.UpdatedAt,
			); err != nil {
				err = fmt.Errorf("BoardList: failed to scan row: %w", err)
				_ = yield(nil, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}

		if err := rows.Err(); err != nil {
			err = fmt.Errorf("BoardList: error iterating rows: %w", err)
			_ = yield(nil, err)
			return
		}
	}
}
