//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"iter"
	"time"

	"github.com/google/cel-go/cel"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
)

// BoardArchiveResult represents the response structure for BoardArchive
type BoardArchiveResult struct {
	ID         int        `json:"id"`
	Name       string     `json:"name"`
	Status     string     `json:"status"`
	ArchivedAt *time.Time `json:"archived_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

// BoardArchive specific CEL programs and mock path
var (
	boardArchivePrograms []cel.Program
)

const boardArchiveMockPath = ""

func init() {

	// CEL environments based on intermediate format
	celEnvironments := make([]*cel.Env, 1)
	// Environment 0 (container: root)
	{
		// Build CEL env options
		opts := []cel.EnvOption{
			cel.Container("root"),
		}
		opts = append(opts,
			cel.HomogeneousAggregateLiterals(),
			cel.EagerlyValidateDeclarations(true),
			snapsqlgo.DecimalLibrary,
		)
		env0, err := cel.NewEnv(opts...)
		if err != nil {
			panic(fmt.Sprintf("failed to create BoardArchive CEL environment 0: %v", err))
		}
		celEnvironments[0] = env0
	}

	// Create programs for each expression using the corresponding environment
	boardArchivePrograms = make([]cel.Program, 0)
}

// BoardArchive Archives the currently active board by switching its status to archived and stamping the archive timestamp. Because only one board can be active at a time, no parameters are required.
func BoardArchive(ctx context.Context, executor snapsqlgo.DBExecutor, opts ...snapsqlgo.FuncOpt) iter.Seq2[*BoardArchiveResult, error] {

	funcConfig := snapsqlgo.GetFunctionConfig(ctx, "boardArchive", "[]boardarchiveresult")

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "UPDATE boards SET status = 'archived', archived_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP  WHERE status = 'active'  RETURNING id, name, status, archived_at, created_at, updated_at"
		args := make([]any, 0)
		return query, args, nil
	}
	return func(yield func(*BoardArchiveResult, error) bool) {
		logger := snapsqlgo.QueryLoggerFromContext(ctx)
		defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
			return snapsqlgo.QueryLogMetadata{
				FuncName:   "BoardArchive",
				SourceFile: "query/BoardArchive",
				Dialect:    "sqlite",
				QueryType:  snapsqlgo.QueryLogQueryTypeSelect,
			}, executor
		})

		query, args, err := buildQueryAndArgs()
		if err != nil {
			logger.SetErr(err)
			_ = yield(nil, err)
			return
		}
		logger.SetQuery(query, args)
		if funcConfig != nil && len(funcConfig.MockDataNames) > 0 {
			mockData, err := snapsqlgo.GetMockDataFromFiles(boardArchiveMockPath, funcConfig.MockDataNames)
			if err != nil {
				logger.SetErr(err)
				_ = yield(nil, fmt.Errorf("BoardArchive: failed to get mock data: %w", err))
				return
			}

			rows, err := snapsqlgo.MapMockDataToStruct[[]BoardArchiveResult](mockData)
			if err != nil {
				logger.SetErr(err)
				_ = yield(nil, fmt.Errorf("BoardArchive: failed to map mock data to []BoardArchiveResult struct: %w", err))
				return
			}

			for i := range rows {
				item := rows[i]
				if !yield(&item, nil) {
					return
				}
			}

			return
		}
		stmt, err := executor.PrepareContext(ctx, query)
		if err != nil {
			err = fmt.Errorf("BoardArchive: failed to prepare statement: %w (query: %s)", err, query)
			logger.SetErr(err)
			_ = yield(nil, err)
			return
		}
		defer stmt.Close()

		rows, err := stmt.QueryContext(ctx, args...)
		if err != nil {
			err = fmt.Errorf("BoardArchive: failed to execute query: %w", err)
			logger.SetErr(err)
			_ = yield(nil, err)
			return
		}
		defer rows.Close()

		for rows.Next() {
			item := new(BoardArchiveResult)
			if err := rows.Scan(
				&item.ID,
				&item.Name,
				&item.Status,
				&item.ArchivedAt,
				&item.CreatedAt,
				&item.UpdatedAt,
			); err != nil {
				err = fmt.Errorf("BoardArchive: failed to scan row: %w", err)
				logger.SetErr(err)
				_ = yield(nil, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}

		if err := rows.Err(); err != nil {
			err = fmt.Errorf("BoardArchive: error iterating rows: %w", err)
			logger.SetErr(err)
			_ = yield(nil, err)
			return
		}
	}
}
