//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
	"time"
)

// BoardCreateResult represents the response structure for BoardCreate
type BoardCreateResult struct {
	ID         int        `json:"id"`
	Name       string     `json:"name"`
	Status     string     `json:"status"`
	ArchivedAt *time.Time `json:"archived_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

// BoardCreateExplangExpressions stores explang steps aligned with expression indexes.
var BoardCreateExplangExpressions = []snapsqlgo.ExplangExpression{
	snapsqlgo.ExplangExpression{
		ID: "expr_001",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "name", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 19, Column: 9, Offset: 0, Length: 4}},
		},
	},
}

const boardCreateMockPath = ""

// BoardCreate Creates a new board using the provided name and returns the persisted row including timestamps.
func BoardCreate(ctx context.Context, executor snapsqlgo.DBExecutor, name string, opts ...snapsqlgo.FuncOpt) (BoardCreateResult, error) {
	var result BoardCreateResult

	// Hierarchical metas (for nested aggregation code generation - placeholder)
	// Count: 0
	// Extract implicit parameters (system arguments). Build specs from explicit
	// ImplicitParams when provided by configuration; otherwise synthesize
	// minimal specs from the SQL builder's ArgumentSystemFields. This ensures
	// generated code that references systemValues always has a declaration,
	// avoiding undefined identifier errors even when the user's config omitted
	// a system section (config defaulting is handled elsewhere).
	implicitSpecs := []snapsqlgo.ImplicitParamSpec{
		{Name: "created_at", Type: "time.Time", Required: false},
		{Name: "updated_at", Type: "time.Time", Required: false},
	}
	systemValues := snapsqlgo.ExtractImplicitParams(ctx, implicitSpecs)
	_ = systemValues // avoid unused if not referenced in args

	execCtx := snapsqlgo.ExtractExecutionContext(ctx)
	rowLockMode := snapsqlgo.RowLockNone
	if execCtx != nil {
		rowLockMode = execCtx.RowLockMode()
	}
	if rowLockMode != snapsqlgo.RowLockNone {
		snapsqlgo.EnsureRowLockAllowed(snapsqlgo.QueryLogQueryTypeExec, rowLockMode)
	}
	rowLockClause := ""
	if rowLockMode != snapsqlgo.RowLockNone {
		var rowLockErr error
		// Call dialect-specific helper generated for each target dialect to avoid runtime dialect checks.
		// SQLite does not support row locks. For SELECT queries we silently ignore the clause;
		// for mutation queries we treat this as an error.
		rowLockClause, rowLockErr = snapsqlgo.BuildRowLockClauseSQLite(rowLockMode)
		if rowLockErr != nil {
			// Return error in a manner appropriate for the function kind (iterator vs normal).
			// non-iterator: return the zero value result and the error
			return result, rowLockErr
		}
	}
	queryLogOptions := snapsqlgo.QueryOptionsSnapshot{
		RowLockClause: rowLockClause,
		RowLockMode:   rowLockMode,
	}

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "INSERT INTO boards (name, status, created_at, updated_at) VALUES ($1, 'active', $2, $3)\n\n RETURNING id, name, status, archived_at, created_at, updated_at"
		args := make([]any, 0)
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(name))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(systemValues["created_at"]))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(systemValues["updated_at"]))
		return query, args, nil
	}
	query, args, err := buildQueryAndArgs()
	if err != nil {
		return result, err
	}
	// Handle mock execution if present
	if mockExec, mockMatched, mockErr := snapsqlgo.MatchMock(ctx, "BoardCreate"); mockMatched {
		if mockErr != nil {
			return result, mockErr
		}
		if mockExec.Err != nil {
			return result, mockExec.Err
		}
		mapped, err := snapsqlgo.MapMockExecutionToStruct[BoardCreateResult](mockExec)
		if err != nil {
			return result, fmt.Errorf("BoardCreate: failed to map mock execution: %w", err)
		}
		result = mapped
		return result, nil
	}
	// Prepare query logger
	logger := execCtx.QueryLogger()
	logger.SetQuery(query, args)
	defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
		return snapsqlgo.QueryLogMetadata{
			FuncName:   "BoardCreate",
			SourceFile: "query/BoardCreate",
			QueryType:  snapsqlgo.QueryLogQueryTypeExec,
			Options:    queryLogOptions,
		}, executor
	})
	// Execute query
	stmt, err := executor.PrepareContext(ctx, query)
	if err != nil {
		err = fmt.Errorf("BoardCreate: failed to prepare statement: %w (query: %s)", err, query)
		return result, err
	}
	defer stmt.Close()
	// Execute query and scan single row
	row := stmt.QueryRowContext(ctx, args...)
	err = row.Scan(
		&result.ID,
		&result.Name,
		&result.Status,
		&result.ArchivedAt,
		&result.CreatedAt,
		&result.UpdatedAt,
	)
	if err != nil {
		return result, fmt.Errorf("failed to scan row: %w", err)
	}

	return result, nil
}
