//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
)

// CardPostponeResult represents the response structure for CardPostpone
type CardPostponeResult struct {
	AffectedRows int `json:"affected_rows"`
}

// CardPostponeExplangExpressions stores explang steps aligned with expression indexes.
var CardPostponeExplangExpressions = []snapsqlgo.ExplangExpression{
	snapsqlgo.ExplangExpression{
		ID: "expr_001",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "src_board_id", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 54, Column: 30, Offset: 0, Length: 12}},
		},
	},
	snapsqlgo.ExplangExpression{
		ID: "expr_002",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "dst_board_id", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 40, Column: 26, Offset: 0, Length: 12}},
		},
	},
}

const cardPostponeMockPath = ""

// CardPostpone Moves all unfinished cards from a source board to the corresponding lists of a destination board created from templates. The destination list is chosen by matching stage_order; lists in the terminal stage (the maximum stage_order on the source board) retain their cards.
func CardPostpone(ctx context.Context, executor snapsqlgo.DBExecutor, srcBoardID int, dstBoardID int, opts ...snapsqlgo.FuncOpt) (sql.Result, error) {
	var result sql.Result

	// Hierarchical metas (for nested aggregation code generation - placeholder)
	// Count: 0

	execCtx := snapsqlgo.ExtractExecutionContext(ctx)
	rowLockMode := snapsqlgo.RowLockNone
	if execCtx != nil {
		rowLockMode = execCtx.RowLockMode()
	}
	if rowLockMode != snapsqlgo.RowLockNone {
		snapsqlgo.EnsureRowLockAllowed(snapsqlgo.QueryLogQueryTypeExec, rowLockMode)
	}
	rowLockClause := ""
	if rowLockMode != snapsqlgo.RowLockNone {
		var rowLockErr error
		// Call dialect-specific helper generated for each target dialect to avoid runtime dialect checks.
		// SQLite does not support row locks. For SELECT queries we silently ignore the clause;
		// for mutation queries we treat this as an error.
		rowLockClause, rowLockErr = snapsqlgo.BuildRowLockClauseSQLite(rowLockMode)
		if rowLockErr != nil {
			// Return error in a manner appropriate for the function kind (iterator vs normal).
			// non-iterator: return the zero value result and the error
			return result, rowLockErr
		}
	}
	queryLogOptions := snapsqlgo.QueryOptionsSnapshot{
		RowLockClause: rowLockClause,
		RowLockMode:   rowLockMode,
	}
	var whereMeta *snapsqlgo.WhereClauseMeta
	whereMeta = &snapsqlgo.WhereClauseMeta{
		Status:  snapsqlgo.WhereClauseStatusExists,
		RawText: "WHERE",
	}

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "WITH done_stage AS ( SELECT stage_order AS stage_limit FROM lists  WHERE board_id = $1  ORDER BY stage_order DESC, id DESC LIMIT 1 ), new_list AS ( SELECT id AS new_list_id FROM lists  WHERE board_id = $2  ORDER BY stage_order ASC, id ASC LIMIT 1 ), undone_lists AS ( SELECT old.id AS old_list_id FROM lists AS old  WHERE old.board_id = $3  AND old.stage_order < ( SELECT stage_limit FROM done_stage ) )UPDATE cards SET list_id = (SELECT new_list_id FROM new_list), updated_at = CURRENT_TIMESTAMP  WHERE list_id IN ( SELECT old_list_id FROM undone_lists )"
		args := make([]any, 0)
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(srcBoardID))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(dstBoardID))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(srcBoardID))
		return query, args, nil
	}
	query, args, err := buildQueryAndArgs()
	if err != nil {
		return nil, err
	}
	// Enforce WHERE clause guard when mutations are generated
	if err := snapsqlgo.EnforceNonEmptyWhereClause(ctx, "CardPostpone", snapsqlgo.MutationUpdate, whereMeta, query); err != nil {
		return nil, err
	}
	// Handle mock execution if present
	if mockExec, mockMatched, mockErr := snapsqlgo.MatchMock(ctx, "CardPostpone"); mockMatched {
		if mockErr != nil {
			return nil, mockErr
		}
		if mockExec.Err != nil {
			return nil, mockExec.Err
		}
		mockResult := mockExec.SQLResult()
		if mockResult == nil {
			mockResult = snapsqlgo.NewMockResult(mockExec.Opt.RowsAffected, mockExec.Opt.LastInsertID)
		}
		if mockResult != nil {
			result = mockResult
		}
		return result, nil
	}
	// Prepare query logger
	logger := execCtx.QueryLogger()
	logger.SetQuery(query, args)
	defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
		return snapsqlgo.QueryLogMetadata{
			FuncName:   "CardPostpone",
			SourceFile: "query/CardPostpone",
			QueryType:  snapsqlgo.QueryLogQueryTypeExec,
			Options:    queryLogOptions,
		}, executor
	})
	// Execute query
	stmt, err := executor.PrepareContext(ctx, query)
	if err != nil {
		err = fmt.Errorf("CardPostpone: failed to prepare statement: %w (query: %s)", err, query)
		return nil, err
	}
	defer stmt.Close()
	// Execute query (no result expected)
	execResult, err := stmt.ExecContext(ctx, args...)
	if err != nil {
		return nil, fmt.Errorf("CardPostpone: failed to execute statement: %w", err)
	}
	result = execResult

	return result, nil
}
