//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"iter"
	"time"

	"github.com/google/cel-go/cel"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
)

// CardCommentListResult represents the response structure for CardCommentList
type CardCommentListResult struct {
	ID        int       `json:"id"`
	CardID    int       `json:"card_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

// CardCommentList specific CEL programs and mock path
var (
	cardCommentListPrograms []cel.Program
)

const cardCommentListMockPath = ""

func init() {

	// CEL environments based on intermediate format
	celEnvironments := make([]*cel.Env, 1)
	// Environment 0: Base environment
	{
		// Build CEL env options then expand variadic at call-site to avoid type inference issues
		opts := []cel.EnvOption{
			cel.HomogeneousAggregateLiterals(),
			cel.EagerlyValidateDeclarations(true),
			snapsqlgo.DecimalLibrary,
			cel.Variable("card_id", cel.IntType),
		}
		env0, err := cel.NewEnv(opts...)
		if err != nil {
			panic(fmt.Sprintf("failed to create CardCommentList CEL environment 0: %v", err))
		}
		celEnvironments[0] = env0
	}

	// Create programs for each expression using the corresponding environment
	cardCommentListPrograms = make([]cel.Program, 1)
	// expr_001: "card_id" using environment 0
	{
		ast, issues := celEnvironments[0].Compile("card_id")
		if issues != nil && issues.Err() != nil {
			panic(fmt.Sprintf("failed to compile CEL expression %q: %v", "card_id", issues.Err()))
		}
		program, err := celEnvironments[0].Program(ast)
		if err != nil {
			panic(fmt.Sprintf("failed to create CEL program for %q: %v", "card_id", err))
		}
		cardCommentListPrograms[0] = program
	}
}

// CardCommentList Retrieves comments associated with a card, ordered by creation time ascending for chronological display.
func CardCommentList(ctx context.Context, executor snapsqlgo.DBExecutor, cardID int, opts ...snapsqlgo.FuncOpt) iter.Seq2[*CardCommentListResult, error] {

	funcConfig := snapsqlgo.GetFunctionConfig(ctx, "cardCommentList", "[]cardcommentlistresult")

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "SELECT id, card_id, body, created_at FROM card_comments  WHERE card_id =$1 OR DER BY created_at ASC, id ASC"
		args := make([]any, 0)
		paramMap := map[string]any{
			"card_id": cardID,
		}

		evalRes0, _, err := cardCommentListPrograms[0].Eval(paramMap)
		if err != nil {
			return "", nil, fmt.Errorf("CardCommentList: failed to evaluate expression: %w", err)
		}
		args = append(args, evalRes0.Value())
		return query, args, nil
	}
	return func(yield func(*CardCommentListResult, error) bool) {
		query, args, err := buildQueryAndArgs()
		if err != nil {
			_ = yield(nil, err)
			return
		}
		if funcConfig != nil && len(funcConfig.MockDataNames) > 0 {
			mockData, err := snapsqlgo.GetMockDataFromFiles(cardCommentListMockPath, funcConfig.MockDataNames)
			if err != nil {
				_ = yield(nil, fmt.Errorf("CardCommentList: failed to get mock data: %w", err))
				return
			}

			rows, err := snapsqlgo.MapMockDataToStruct[[]CardCommentListResult](mockData)
			if err != nil {
				_ = yield(nil, fmt.Errorf("CardCommentList: failed to map mock data to []CardCommentListResult struct: %w", err))
				return
			}

			for i := range rows {
				item := rows[i]
				if !yield(&item, nil) {
					return
				}
			}

			return
		}
		stmt, err := executor.PrepareContext(ctx, query)
		if err != nil {
			_ = yield(nil, fmt.Errorf("CardCommentList: failed to prepare statement: %w", err))
			return
		}
		defer stmt.Close()

		rows, err := stmt.QueryContext(ctx, args...)
		if err != nil {
			_ = yield(nil, fmt.Errorf("CardCommentList: failed to execute query: %w", err))
			return
		}
		defer rows.Close()

		for rows.Next() {
			item := new(CardCommentListResult)
			if err := rows.Scan(
				&item.ID,
				&item.CardID,
				&item.Body,
				&item.CreatedAt,
			); err != nil {
				_ = yield(nil, fmt.Errorf("CardCommentList: failed to scan row: %w", err))
				return
			}
			if !yield(item, nil) {
				return
			}
		}

		if err := rows.Err(); err != nil {
			_ = yield(nil, fmt.Errorf("CardCommentList: error iterating rows: %w", err))
			return
		}
	}
}
