//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"iter"
	"time"

	"github.com/google/cel-go/cel"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
)

// CardMoveResult represents the response structure for CardMove
type CardMoveResult struct {
	ID          int       `json:"id"`
	ListID      int       `json:"list_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Position    float64   `json:"position"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// CardMove specific CEL programs and mock path
var (
	cardMovePrograms []cel.Program
)

const cardMoveMockPath = ""

func init() {

	// CEL environments based on intermediate format
	celEnvironments := make([]*cel.Env, 1)
	// Environment 0 (container: root)
	{
		// Build CEL env options
		opts := []cel.EnvOption{
			cel.Container("root"),
		}
		opts = append(opts, cel.Variable("card_id", cel.IntType))
		opts = append(opts, cel.Variable("target_list_id", cel.IntType))
		opts = append(opts, cel.Variable("target_position", cel.DoubleType))
		opts = append(opts,
			cel.HomogeneousAggregateLiterals(),
			cel.EagerlyValidateDeclarations(true),
			snapsqlgo.DecimalLibrary,
		)
		env0, err := cel.NewEnv(opts...)
		if err != nil {
			panic(fmt.Sprintf("failed to create CardMove CEL environment 0: %v", err))
		}
		celEnvironments[0] = env0
	}

	// Create programs for each expression using the corresponding environment
	cardMovePrograms = make([]cel.Program, 3)
	// expr_001: "target_list_id" using environment 0
	{
		ast, issues := celEnvironments[0].Compile("target_list_id")
		if issues != nil && issues.Err() != nil {
			panic(fmt.Sprintf("failed to compile CEL expression %q: %v", "target_list_id", issues.Err()))
		}
		program, err := celEnvironments[0].Program(ast)
		if err != nil {
			panic(fmt.Sprintf("failed to create CEL program for %q: %v", "target_list_id", err))
		}
		cardMovePrograms[0] = program
	}
	// expr_002: "target_position" using environment 0
	{
		ast, issues := celEnvironments[0].Compile("target_position")
		if issues != nil && issues.Err() != nil {
			panic(fmt.Sprintf("failed to compile CEL expression %q: %v", "target_position", issues.Err()))
		}
		program, err := celEnvironments[0].Program(ast)
		if err != nil {
			panic(fmt.Sprintf("failed to create CEL program for %q: %v", "target_position", err))
		}
		cardMovePrograms[1] = program
	}
	// expr_003: "card_id" using environment 0
	{
		ast, issues := celEnvironments[0].Compile("card_id")
		if issues != nil && issues.Err() != nil {
			panic(fmt.Sprintf("failed to compile CEL expression %q: %v", "card_id", issues.Err()))
		}
		program, err := celEnvironments[0].Program(ast)
		if err != nil {
			panic(fmt.Sprintf("failed to create CEL program for %q: %v", "card_id", err))
		}
		cardMovePrograms[2] = program
	}
}

// CardMove Moves a card to a target list and position, using a transactional update for drag-and-drop operations.
func CardMove(ctx context.Context, executor snapsqlgo.DBExecutor, cardID int, targetListID int, targetPosition float64, opts ...snapsqlgo.FuncOpt) iter.Seq2[*CardMoveResult, error] {

	funcConfig := snapsqlgo.GetFunctionConfig(ctx, "cardMove", "[]cardmoveresult")
	// Extract implicit parameters
	implicitSpecs := []snapsqlgo.ImplicitParamSpec{
		{Name: "updated_at", Type: "time.Time", Required: false, DefaultValue: "CURRENT_TIMESTAMP"},
	}
	systemValues := snapsqlgo.ExtractImplicitParams(ctx, implicitSpecs)
	_ = systemValues // avoid unused if not referenced in args

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "UPDATE cards SET list_id =$1, position =$2, updated_at =$3  WHERE id =$4  RETURNING id, list_id, title, description, position, created_at, updated_at"
		args := make([]any, 0)
		paramMap := map[string]any{
			"card_id":         cardID,
			"target_list_id":  targetListID,
			"target_position": targetPosition,
		}

		evalRes0, _, err := cardMovePrograms[0].Eval(paramMap)
		if err != nil {
			return "", nil, fmt.Errorf("CardMove: failed to evaluate expression: %w", err)
		}
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(evalRes0))

		evalRes1, _, err := cardMovePrograms[1].Eval(paramMap)
		if err != nil {
			return "", nil, fmt.Errorf("CardMove: failed to evaluate expression: %w", err)
		}
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(evalRes1))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(systemValues["updated_at"]))

		evalRes3, _, err := cardMovePrograms[2].Eval(paramMap)
		if err != nil {
			return "", nil, fmt.Errorf("CardMove: failed to evaluate expression: %w", err)
		}
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(evalRes3))
		return query, args, nil
	}
	return func(yield func(*CardMoveResult, error) bool) {
		query, args, err := buildQueryAndArgs()
		if err != nil {
			_ = yield(nil, err)
			return
		}
		if funcConfig != nil && len(funcConfig.MockDataNames) > 0 {
			mockData, err := snapsqlgo.GetMockDataFromFiles(cardMoveMockPath, funcConfig.MockDataNames)
			if err != nil {
				_ = yield(nil, fmt.Errorf("CardMove: failed to get mock data: %w", err))
				return
			}

			rows, err := snapsqlgo.MapMockDataToStruct[[]CardMoveResult](mockData)
			if err != nil {
				_ = yield(nil, fmt.Errorf("CardMove: failed to map mock data to []CardMoveResult struct: %w", err))
				return
			}

			for i := range rows {
				item := rows[i]
				if !yield(&item, nil) {
					return
				}
			}

			return
		}
		stmt, err := executor.PrepareContext(ctx, query)
		if err != nil {
			_ = yield(nil, fmt.Errorf("CardMove: failed to prepare statement: %w (query: %s)", err, query))
			return
		}
		defer stmt.Close()

		rows, err := stmt.QueryContext(ctx, args...)
		if err != nil {
			_ = yield(nil, fmt.Errorf("CardMove: failed to execute query: %w", err))
			return
		}
		defer rows.Close()

		for rows.Next() {
			item := new(CardMoveResult)
			if err := rows.Scan(
				&item.ID,
				&item.ListID,
				&item.Title,
				&item.Description,
				&item.Position,
				&item.CreatedAt,
				&item.UpdatedAt,
			); err != nil {
				_ = yield(nil, fmt.Errorf("CardMove: failed to scan row: %w", err))
				return
			}
			if !yield(item, nil) {
				return
			}
		}

		if err := rows.Err(); err != nil {
			_ = yield(nil, fmt.Errorf("CardMove: error iterating rows: %w", err))
			return
		}
	}
}
