//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"time"

	"github.com/google/cel-go/cel"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
)

// CardCreateResult represents the response structure for CardCreate
type CardCreateResult struct {
	ID          int       `json:"id"`
	ListID      int       `json:"list_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Position    float64   `json:"position"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// CardCreate specific CEL programs and mock path
var (
	cardCreatePrograms []cel.Program
)

const cardCreateMockPath = ""

func init() {

	// CEL environments based on intermediate format
	celEnvironments := make([]*cel.Env, 1)
	// Environment 0 (container: root)
	{
		// Build CEL env options
		opts := []cel.EnvOption{
			cel.Container("root"),
		}
		opts = append(opts, cel.Variable("title", cel.StringType))
		opts = append(opts, cel.Variable("description", cel.StringType))
		opts = append(opts, cel.Variable("position", cel.DoubleType))
		opts = append(opts, cel.Variable("title", cel.StringType))
		opts = append(opts, cel.Variable("description", cel.StringType))
		opts = append(opts, cel.Variable("position", cel.DoubleType))
		opts = append(opts, cel.Variable("title", cel.StringType))
		opts = append(opts, cel.Variable("description", cel.StringType))
		opts = append(opts, cel.Variable("position", cel.DoubleType))
		opts = append(opts,
			cel.HomogeneousAggregateLiterals(),
			cel.EagerlyValidateDeclarations(true),
			snapsqlgo.DecimalLibrary,
		)
		env0, err := cel.NewEnv(opts...)
		if err != nil {
			panic(fmt.Sprintf("failed to create CardCreate CEL environment 0: %v", err))
		}
		celEnvironments[0] = env0
	}

	// Create programs for each expression using the corresponding environment
	cardCreatePrograms = make([]cel.Program, 3)
	// expr_001: "title" using environment 0
	{
		ast, issues := celEnvironments[0].Compile("title")
		if issues != nil && issues.Err() != nil {
			panic(fmt.Sprintf("failed to compile CEL expression %q: %v", "title", issues.Err()))
		}
		program, err := celEnvironments[0].Program(ast)
		if err != nil {
			panic(fmt.Sprintf("failed to create CEL program for %q: %v", "title", err))
		}
		cardCreatePrograms[0] = program
	}
	// expr_002: "description" using environment 0
	{
		ast, issues := celEnvironments[0].Compile("description")
		if issues != nil && issues.Err() != nil {
			panic(fmt.Sprintf("failed to compile CEL expression %q: %v", "description", issues.Err()))
		}
		program, err := celEnvironments[0].Program(ast)
		if err != nil {
			panic(fmt.Sprintf("failed to create CEL program for %q: %v", "description", err))
		}
		cardCreatePrograms[1] = program
	}
	// expr_003: "position" using environment 0
	{
		ast, issues := celEnvironments[0].Compile("position")
		if issues != nil && issues.Err() != nil {
			panic(fmt.Sprintf("failed to compile CEL expression %q: %v", "position", issues.Err()))
		}
		program, err := celEnvironments[0].Program(ast)
		if err != nil {
			panic(fmt.Sprintf("failed to create CEL program for %q: %v", "position", err))
		}
		cardCreatePrograms[2] = program
	}
}

// CardCreate Creates a card within a list and returns the inserted row for client-side refresh.
func CardCreate(ctx context.Context, executor snapsqlgo.DBExecutor, title string, description string, position float64, opts ...snapsqlgo.FuncOpt) (CardCreateResult, error) {
	var result CardCreateResult

	// Hierarchical metas (for nested aggregation code generation - placeholder)
	// Count: 0

	funcConfig := snapsqlgo.GetFunctionConfig(ctx, "cardCreate", "cardcreateresult")
	// Check for mock mode
	if funcConfig != nil && len(funcConfig.MockDataNames) > 0 {
		mockData, err := snapsqlgo.GetMockDataFromFiles(cardCreateMockPath, funcConfig.MockDataNames)
		if err != nil {
			return result, fmt.Errorf("CardCreate: failed to get mock data: %w", err)
		}

		result, err = snapsqlgo.MapMockDataToStruct[CardCreateResult](mockData)
		if err != nil {
			return result, fmt.Errorf("CardCreate: failed to map mock data to CardCreateResult struct: %w", err)
		}

		return result, nil
	}
	// Extract implicit parameters
	implicitSpecs := []snapsqlgo.ImplicitParamSpec{
		{Name: "created_at", Type: "time.Time", Required: false},
		{Name: "updated_at", Type: "time.Time", Required: false},
	}
	systemValues := snapsqlgo.ExtractImplicitParams(ctx, implicitSpecs)
	_ = systemValues // avoid unused if not referenced in args

	execCtx := snapsqlgo.ExtractExecutionContext(ctx)
	rowLockMode := snapsqlgo.RowLockNone
	if execCtx != nil {
		rowLockMode = execCtx.RowLockMode()
	}
	if rowLockMode != snapsqlgo.RowLockNone {
		snapsqlgo.EnsureRowLockAllowed(snapsqlgo.QueryLogQueryTypeExec, rowLockMode)
	}
	rowLockClause := ""
	if rowLockMode != snapsqlgo.RowLockNone {
		var rowLockErr error
		rowLockClause, rowLockErr = snapsqlgo.BuildRowLockClause("sqlite", rowLockMode)
		if rowLockErr != nil {
			panic(rowLockErr)
		}
	}
	queryLogOptions := snapsqlgo.QueryOptionsSnapshot{
		RowLockClause: rowLockClause,
		RowLockMode:   rowLockMode,
	}
	logger := execCtx.QueryLogger()
	defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
		return snapsqlgo.QueryLogMetadata{
			FuncName:   "CardCreate",
			SourceFile: "query/CardCreate",
			Dialect:    "sqlite",
			QueryType:  snapsqlgo.QueryLogQueryTypeExec,
			Options:    queryLogOptions,
		}, executor
	})

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "INSERT INTO cards ( list_id, title, description, position , created_at, updated_at) VALUES ( (SELECT l.id FROM lists AS l JOIN boards b ON l.board_id = b.id  WHERE b.status = 'active' ORDER BY l.stage_order ASC LIMIT 1), $1, $2, $3 , $4, $5)\n\n RETURNING id, list_id, title, description, position, created_at, updated_at"
		args := make([]any, 0)
		paramMap := map[string]any{
			"title":       title,
			"description": description,
			"position":    position,
		}

		evalRes0, _, err := cardCreatePrograms[0].Eval(paramMap)
		if err != nil {
			return "", nil, fmt.Errorf("CardCreate: failed to evaluate expression: %w", err)
		}
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(evalRes0))

		evalRes1, _, err := cardCreatePrograms[1].Eval(paramMap)
		if err != nil {
			return "", nil, fmt.Errorf("CardCreate: failed to evaluate expression: %w", err)
		}
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(evalRes1))

		evalRes2, _, err := cardCreatePrograms[2].Eval(paramMap)
		if err != nil {
			return "", nil, fmt.Errorf("CardCreate: failed to evaluate expression: %w", err)
		}
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(evalRes2))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(systemValues["created_at"]))

		args = append(args, snapsqlgo.NormalizeNullableTimestamp(systemValues["updated_at"]))

		return query, args, nil
	}
	query, args, err := buildQueryAndArgs()
	if err != nil {
		logger.SetErr(err)
		return result, err
	}
	logger.SetQuery(query, args)
	// Execute query
	stmt, err := executor.PrepareContext(ctx, query)
	if err != nil {
		err = fmt.Errorf("CardCreate: failed to prepare statement: %w (query: %s)", err, query)
		logger.SetErr(err)
		return result, err
	}
	defer stmt.Close()
	// Execute query and scan single row
	row := stmt.QueryRowContext(ctx, args...)
	err = row.Scan(
		&result.ID,
		&result.ListID,
		&result.Title,
		&result.Description,
		&result.Position,
		&result.CreatedAt,
		&result.UpdatedAt,
	)
	if err != nil {
		err = fmt.Errorf("failed to scan row: %w", err)
		logger.SetErr(err)
		return result, err
	}

	return result, nil
}
