//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package query

import (
	"context"
	"fmt"
	"iter"
	"time"

	"github.com/google/cel-go/cel"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
)

// ListRenameResult represents the response structure for ListRename
type ListRenameResult struct {
	ID         int       `json:"id"`
	BoardID    int       `json:"board_id"`
	Name       string    `json:"name"`
	StageOrder int       `json:"stage_order"`
	Position   float64   `json:"position"`
	IsArchived int       `json:"is_archived"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// ListRename specific CEL programs and mock path
var (
	listrenamePrograms []cel.Program
)

const listrenameMockPath = ""

func init() {

	// CEL environments based on intermediate format
	celEnvironments := make([]*cel.Env, 1)
	// Environment 0: Base environment
	{
		// Build CEL env options then expand variadic at call-site to avoid type inference issues
		opts := []cel.EnvOption{
			cel.HomogeneousAggregateLiterals(),
			cel.EagerlyValidateDeclarations(true),
			snapsqlgo.DecimalLibrary,
			cel.Variable("list_id", cel.IntType),
			cel.Variable("name", cel.StringType),
		}
		env0, err := cel.NewEnv(opts...)
		if err != nil {
			panic(fmt.Sprintf("failed to create ListRename CEL environment 0: %v", err))
		}
		celEnvironments[0] = env0
	}

	// Create programs for each expression using the corresponding environment
	listrenamePrograms = make([]cel.Program, 2)
	// expr_001: "name" using environment 0
	{
		ast, issues := celEnvironments[0].Compile("name")
		if issues != nil && issues.Err() != nil {
			panic(fmt.Sprintf("failed to compile CEL expression %q: %v", "name", issues.Err()))
		}
		program, err := celEnvironments[0].Program(ast)
		if err != nil {
			panic(fmt.Sprintf("failed to create CEL program for %q: %v", "name", err))
		}
		listrenamePrograms[0] = program
	}
	// expr_002: "list_id" using environment 0
	{
		ast, issues := celEnvironments[0].Compile("list_id")
		if issues != nil && issues.Err() != nil {
			panic(fmt.Sprintf("failed to compile CEL expression %q: %v", "list_id", issues.Err()))
		}
		program, err := celEnvironments[0].Program(ast)
		if err != nil {
			panic(fmt.Sprintf("failed to create CEL program for %q: %v", "list_id", err))
		}
		listrenamePrograms[1] = program
	}
}

// ListRename Renames a list and updates its timestamp for optimistic concurrency.
func ListRename(ctx context.Context, executor snapsqlgo.DBExecutor, listID int, name string, opts ...snapsqlgo.FuncOpt) iter.Seq2[*ListRenameResult, error] {

	funcConfig := snapsqlgo.GetFunctionConfig(ctx, "listrename", "[]listrenameresult")
	// Extract implicit parameters
	implicitSpecs := []snapsqlgo.ImplicitParamSpec{
		{Name: "updated_at", Type: "time.Time", Required: false, DefaultValue: "CURRENT_TIMESTAMP"},
	}
	systemValues := snapsqlgo.ExtractImplicitParams(ctx, implicitSpecs)
	_ = systemValues // avoid unused if not referenced in args

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "UPDATE lists SET name =$1, updated_at =$2  WHERE id =$3  RETURNING id, board_id, name, stage_order, position, is_archived, created_at, updated_at"
		args := make([]any, 0)
		paramMap := map[string]any{
			"list_id": listID,
			"name":    name,
		}

		evalRes0, _, err := listrenamePrograms[0].Eval(paramMap)
		if err != nil {
			return "", nil, fmt.Errorf("ListRename: failed to evaluate expression: %w", err)
		}
		args = append(args, evalRes0.Value())
		args = append(args, systemValues["updated_at"])

		evalRes2, _, err := listrenamePrograms[1].Eval(paramMap)
		if err != nil {
			return "", nil, fmt.Errorf("ListRename: failed to evaluate expression: %w", err)
		}
		args = append(args, evalRes2.Value())
		return query, args, nil
	}
	return func(yield func(*ListRenameResult, error) bool) {
		query, args, err := buildQueryAndArgs()
		if err != nil {
			_ = yield(nil, err)
			return
		}
		if funcConfig != nil && len(funcConfig.MockDataNames) > 0 {
			mockData, err := snapsqlgo.GetMockDataFromFiles(listrenameMockPath, funcConfig.MockDataNames)
			if err != nil {
				_ = yield(nil, fmt.Errorf("ListRename: failed to get mock data: %w", err))
				return
			}

			rows, err := snapsqlgo.MapMockDataToStruct[[]ListRenameResult](mockData)
			if err != nil {
				_ = yield(nil, fmt.Errorf("ListRename: failed to map mock data to []ListRenameResult struct: %w", err))
				return
			}

			for i := range rows {
				item := rows[i]
				if !yield(&item, nil) {
					return
				}
			}

			return
		}
		stmt, err := executor.PrepareContext(ctx, query)
		if err != nil {
			_ = yield(nil, fmt.Errorf("ListRename: failed to prepare statement: %w", err))
			return
		}
		defer stmt.Close()

		rows, err := stmt.QueryContext(ctx, args...)
		if err != nil {
			_ = yield(nil, fmt.Errorf("ListRename: failed to execute query: %w", err))
			return
		}
		defer rows.Close()

		for rows.Next() {
			item := new(ListRenameResult)
			if err := rows.Scan(
				&item.ID,
				&item.BoardID,
				&item.Name,
				&item.StageOrder,
				&item.Position,
				&item.IsArchived,
				&item.CreatedAt,
				&item.UpdatedAt,
			); err != nil {
				_ = yield(nil, fmt.Errorf("ListRename: failed to scan row: %w", err))
				return
			}
			if !yield(item, nil) {
				return
			}
		}

		if err := rows.Err(); err != nil {
			_ = yield(nil, fmt.Errorf("ListRename: error iterating rows: %w", err))
			return
		}
	}
}
