# Generated by snapsql - DO NOT EDIT
# Generated at: 2025-11-21T00:48:17+09:00
# Function: GetAccountWithPosts
# Dialect: sqlite

"""

"""

from dataclasses import dataclass, asdict
from typing import Optional, List, Any, Dict, AsyncGenerator, Union
from datetime import datetime
from decimal import Decimal
from .snapsql_runtime import (
    get_snapsql_context,
    ValidationError,
    QueryLogMetadata,
)
# SQLite async driver
try:
    import aiosqlite
except ImportError:
    raise ImportError("aiosqlite is required for SQLite. Install with: pip install aiosqlite")

# ============================================================================
# Response Structures
# ============================================================================

@dataclass
class GetAccountWithPostsResultPosts:
    """Response structure for GetAccountWithPosts"""
    title: str
    id: Optional[int] = None
    body: Optional[str] = None
    published_at: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization"""
        return asdict(self)

@dataclass
class GetAccountWithPostsResult:
    """Response structure for GetAccountWithPosts"""
    id: Optional[int] = None
    name: Optional[str] = None
    status: Optional[str] = None
    posts: List[GetAccountWithPostsResultPosts] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization"""
        return asdict(self)


# ============================================================================
# Generated Functions
# ============================================================================
async def get_account_with_posts(
    cursor: Union[aiosqlite.cursor.Cursor, aiosqlite.Connection],
    account_id: int,
) -> GetAccountWithPostsResult:
    """
    
    
    Args:
        account_id: 
    
    Returns:
        Result of GetAccountWithPosts
    """
    # Validate required parameters
    if account_id is None:
        raise ValidationError(
            message="Required parameter 'account_id' cannot be None",
            param_name="account_id",
            func_name="GetAccountWithPosts"
        )
    
    # Build SQL
    sql = """SELECT a.id, a.name, a.status, p.id AS posts__id, p.title AS posts__title, p.body AS posts__body, p.published_at AS posts__published_at FROM accounts a LEFT JOIN posts p ON p.account_id = a.id WHERE a.id = ? ORDER BY p.id """
    args = [account_id]

    ctx = get_snapsql_context()
    logger = ctx.query_logger if ctx.enable_query_log else None
    error = None
    row_count = None
    import time
    start_time = time.time()
    try:
        # Execute query for hierarchical aggregation (one affinity)
        # This aggregates multiple rows into a single parent object with child lists

        if isinstance(cursor, aiosqlite.Connection):
            cursor = await cursor.execute(sql, args)
        else:
            await cursor.execute(sql, args)

        # Collect all rows first
        rows = []
        async for row in cursor:
            rows.append(row if isinstance(row, dict) else dict(row))

        if not rows:
            raise NotFoundError(
                message="Record not found",
                func_name="GetAccountWithPosts",
                query=sql
            )

        # Process rows for hierarchical aggregation
        result = None

        for row_dict in rows:
            
            # Create parent object on first row
            if result is None:
                result = GetAccountWithPostsResult(
                    id=row_dict.get('id'),
                    name=row_dict.get('name'),
                    status=row_dict.get('status'),
                    posts=[]
                )
            
            # Add child objects if present
            if any([row_dict.get('posts__id'), row_dict.get('posts__title'), row_dict.get('posts__body'), row_dict.get('posts__published_at')]):
                child_obj = GetAccountWithPostsResultPosts(
                    id=row_dict.get('posts__id'),
                    title=row_dict.get('posts__title'),
                    body=row_dict.get('posts__body'),
                    published_at=row_dict.get('posts__published_at')
                )
                result.posts.append(child_obj)

        return result
    except Exception as err:
        error = err
        raise
    finally:
        if logger:
            duration_ms = (time.time() - start_time) * 1000
            metadata = QueryLogMetadata(
                func_name="GetAccountWithPosts",
                source_file="GetAccountWithPosts",
                dialect="sqlite",
                query_type="select"
            )
            await logger.write(metadata, duration_ms, row_count, error)
