# Generated by snapsql - DO NOT EDIT
# Generated at: 2025-11-21T00:48:17+09:00
# Function: AccountGet
# Dialect: sqlite

"""

"""

from dataclasses import dataclass, asdict
from typing import Optional, List, Any, Dict, AsyncGenerator, Union
from datetime import datetime
from decimal import Decimal
from .snapsql_runtime import (
    get_snapsql_context,
    ValidationError,
    NotFoundError,
    QueryLogMetadata,
)
# SQLite async driver
try:
    import aiosqlite
except ImportError:
    raise ImportError("aiosqlite is required for SQLite. Install with: pip install aiosqlite")

# ============================================================================
# Response Structures
# ============================================================================

@dataclass
class AccountGetResult:
    """Response structure for AccountGet"""
    id: Optional[int] = None
    name: Optional[str] = None
    status: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization"""
        return asdict(self)


# ============================================================================
# Generated Functions
# ============================================================================
async def account_get(
    cursor: Union[aiosqlite.cursor.Cursor, aiosqlite.Connection],
    account_id: int,
) -> AccountGetResult:
    """
    
    
    Args:
        account_id: 
    
    Returns:
        Result of AccountGet
    """
    # Validate required parameters
    if account_id is None:
        raise ValidationError(
            message="Required parameter 'account_id' cannot be None",
            param_name="account_id",
            func_name="AccountGet"
        )
    
    # Build SQL
    sql = """SELECT id, name, status FROM accounts WHERE id = ? """
    args = [account_id]

    ctx = get_snapsql_context()
    logger = ctx.query_logger if ctx.enable_query_log else None
    error = None
    row_count = None
    import time
    start_time = time.time()
    try:
        # Execute query and fetch single row
        if isinstance(cursor, aiosqlite.Connection):
            cursor = await cursor.execute(sql, args)
        else:
            await cursor.execute(sql, args)

        row = await cursor.fetchone()

        if row is None:
            # Build parameter dict for error message
            param_dict = {}
            # Note: args is a list, parameter names would need to be tracked separately
            raise NotFoundError(
                message="Record not found",
                func_name="AccountGet",
                query=sql,
                params=param_dict
            )

        # Map row to dataclass
        # aiosqlite with row_factory returns dict-like object
        return AccountGetResult(**row)
    except Exception as err:
        error = err
        raise
    finally:
        if logger:
            duration_ms = (time.time() - start_time) * 1000
            metadata = QueryLogMetadata(
                func_name="AccountGet",
                source_file="AccountGet",
                dialect="sqlite",
                query_type="select"
            )
            await logger.write(metadata, duration_ms, row_count, error)
