# Generated by snapsql - DO NOT EDIT
# Generated at: 2025-11-21T00:48:17+09:00
# Function: AccountUpdate
# Dialect: sqlite

"""

"""

from dataclasses import dataclass, asdict
from typing import Optional, List, Any, Dict, AsyncGenerator, Union
from datetime import datetime
from decimal import Decimal
from .snapsql_runtime import (
    get_snapsql_context,
    ValidationError,
    QueryLogMetadata,
)
# SQLite async driver
try:
    import aiosqlite
except ImportError:
    raise ImportError("aiosqlite is required for SQLite. Install with: pip install aiosqlite")

# ============================================================================
# Response Structures
# ============================================================================

@dataclass
class AccountUpdateResult:
    """Response structure for AccountUpdate"""
    id: Optional[int] = None
    status: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization"""
        return asdict(self)


# ============================================================================
# Generated Functions
# ============================================================================
async def account_update(
    cursor: Union[aiosqlite.cursor.Cursor, aiosqlite.Connection],
    account_id: int,
    status: str,
) -> AsyncGenerator[AccountUpdateResult, None]:
    """
    
    
    Args:
        account_id: 
        status: 
    
    Returns:
        Result of AccountUpdate
    """
    # Validate required parameters
    if account_id is None:
        raise ValidationError(
            message="Required parameter 'account_id' cannot be None",
            param_name="account_id",
            func_name="AccountUpdate"
        )
    if status is None:
        raise ValidationError(
            message="Required parameter 'status' cannot be None",
            param_name="status",
            func_name="AccountUpdate"
        )
    
    # Build SQL
    sql = """UPDATE accounts SET status = ? WHERE id = ? RETURNING id, status"""
    args = [status, account_id]

    ctx = get_snapsql_context()
    logger = ctx.query_logger if ctx.enable_query_log else None
    error = None
    row_count = None
    import time
    start_time = time.time()
    try:
        # Execute query and yield rows as async generator
        await cursor.execute(sql, args)

        # Fetch and yield rows
        async for row in cursor:
            yield AccountUpdateResult(**row)
    except Exception as err:
        error = err
        raise
    finally:
        if logger:
            duration_ms = (time.time() - start_time) * 1000
            metadata = QueryLogMetadata(
                func_name="AccountUpdate",
                source_file="AccountUpdate",
                dialect="sqlite",
                query_type="update"
            )
            await logger.write(metadata, duration_ms, row_count, error)
