# Generated by snapsql - DO NOT EDIT
# Generated at: 2025-11-21T00:48:17+09:00
# Function: AccountList
# Dialect: sqlite

"""

"""

from dataclasses import dataclass, asdict
from typing import Optional, List, Any, Dict, AsyncGenerator, Union
from datetime import datetime
from decimal import Decimal
from .snapsql_runtime import (
    get_snapsql_context,
    QueryLogMetadata,
)
# SQLite async driver
try:
    import aiosqlite
except ImportError:
    raise ImportError("aiosqlite is required for SQLite. Install with: pip install aiosqlite")

# ============================================================================
# Response Structures
# ============================================================================

@dataclass
class AccountListResult:
    """Response structure for AccountList"""
    id: Optional[int] = None
    name: Optional[str] = None
    status: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization"""
        return asdict(self)


# ============================================================================
# Generated Functions
# ============================================================================
async def account_list(
    cursor: Union[aiosqlite.cursor.Cursor, aiosqlite.Connection],
) -> AsyncGenerator[AccountListResult, None]:
    """
    
    
    Args:
    
    Returns:
        Result of AccountList
    """
    
    # Build SQL
    sql = """SELECT id, name, status FROM accounts ORDER BY id DESC """
    args = []

    ctx = get_snapsql_context()
    logger = ctx.query_logger if ctx.enable_query_log else None
    error = None
    row_count = None
    import time
    start_time = time.time()
    try:
        # Execute query and yield rows as async generator
        await cursor.execute(sql, args)

        # Fetch and yield rows
        async for row in cursor:
            yield AccountListResult(**row)
    except Exception as err:
        error = err
        raise
    finally:
        if logger:
            duration_ms = (time.time() - start_time) * 1000
            metadata = QueryLogMetadata(
                func_name="AccountList",
                source_file="AccountList",
                dialect="sqlite",
                query_type="select"
            )
            await logger.write(metadata, duration_ms, row_count, error)
