//go:build !ignore_autogenerated

// Code generated by snapsql. DO NOT EDIT.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package appsample

import (
	"context"
	"fmt"
	"github.com/shibukawa/snapsql/langs/snapsqlgo"
	"iter"
)

// AccountUpdateResult represents the response structure for AccountUpdate
type AccountUpdateResult struct {
	ID     int     `json:"id"`
	Status *string `json:"status"`
}

// AccountUpdateExplangExpressions stores explang steps aligned with expression indexes.
var AccountUpdateExplangExpressions = []snapsqlgo.ExplangExpression{
	snapsqlgo.ExplangExpression{
		ID: "expr_001",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "status", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 9, Column: 14, Offset: 0, Length: 6}},
		},
	},
	snapsqlgo.ExplangExpression{
		ID: "expr_002",
		Expressions: []snapsqlgo.Expression{
			{Kind: snapsqlgo.ExpressionIdentifier, Identifier: "account_id", Property: "", Index: 0, Safe: false, Position: snapsqlgo.ExpPosition{Line: 10, Column: 12, Offset: 0, Length: 10}},
		},
	},
}

const accountUpdateMockPath = ""

// AccountUpdate - []AccountUpdateResult Affinity
func AccountUpdate(ctx context.Context, executor snapsqlgo.DBExecutor, accountID int, status string, opts ...snapsqlgo.FuncOpt) iter.Seq2[*AccountUpdateResult, error] {

	execCtx := snapsqlgo.ExtractExecutionContext(ctx)
	rowLockMode := snapsqlgo.RowLockNone
	if execCtx != nil {
		rowLockMode = execCtx.RowLockMode()
	}
	if rowLockMode != snapsqlgo.RowLockNone {
		snapsqlgo.EnsureRowLockAllowed(snapsqlgo.QueryLogQueryTypeExec, rowLockMode)
	}
	rowLockClause := ""
	if rowLockMode != snapsqlgo.RowLockNone {
		var rowLockErr error
		// Call dialect-specific helper generated for each target dialect to avoid runtime dialect checks.
		// SQLite does not support row locks. For SELECT queries we silently ignore the clause;
		// for mutation queries we treat this as an error.
		rowLockClause, rowLockErr = snapsqlgo.BuildRowLockClauseSQLite(rowLockMode)
		if rowLockErr != nil {
			// Return error in a manner appropriate for the function kind (iterator vs normal).
			var zero *AccountUpdateResult
			return func(yield func(*AccountUpdateResult, error) bool) {
				// yield the error to the caller and exit the iterator function
				_ = yield(zero, rowLockErr)
				return
			}
		}
	}
	queryLogOptions := snapsqlgo.QueryOptionsSnapshot{
		RowLockClause: rowLockClause,
		RowLockMode:   rowLockMode,
	}
	var whereMeta *snapsqlgo.WhereClauseMeta
	whereMeta = &snapsqlgo.WhereClauseMeta{
		Status:  snapsqlgo.WhereClauseStatusExists,
		RawText: "WHERE",
	}

	// Build SQL
	buildQueryAndArgs := func() (string, []any, error) {
		query := "UPDATE accounts SET status = $1   WHERE id = $2   RETURNING id, status"
		args := make([]any, 0)
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(status))
		args = append(args, snapsqlgo.NormalizeNullableTimestamp(accountID))
		return query, args, nil
	}
	return func(yield func(*AccountUpdateResult, error) bool) {
		query, args, err := buildQueryAndArgs()
		if err != nil {
			_ = yield(nil, err)
			return
		}
		// Enforce WHERE clause guard when mutations are generated
		if err := snapsqlgo.EnforceNonEmptyWhereClause(ctx, "AccountUpdate", snapsqlgo.MutationUpdate, whereMeta, query); err != nil {
			_ = yield(nil, err)
			return
		}
		// Handle mock execution if present
		if mockExec, mockMatched, mockErr := snapsqlgo.MatchMock(ctx, "AccountUpdate"); mockMatched {
			if mockErr != nil {
				_ = yield(nil, mockErr)
				return
			}
			if mockExec.Err != nil {
				_ = yield(nil, mockExec.Err)
				return
			}

			mapped, err := snapsqlgo.MapMockExecutionToSlice[AccountUpdateResult](mockExec)
			if err != nil {
				_ = yield(nil, fmt.Errorf("AccountUpdate: failed to map mock execution: %w", err))
				return
			}

			for i := range mapped {
				item := mapped[i]
				if !yield(&item, nil) {
					return
				}
			}

			return
		}
		// Prepare query logger
		logger := execCtx.QueryLogger()
		logger.SetQuery(query, args)
		defer logger.Write(ctx, func() (snapsqlgo.QueryLogMetadata, snapsqlgo.DBExecutor) {
			return snapsqlgo.QueryLogMetadata{
				FuncName:   "AccountUpdate",
				SourceFile: "appsample/AccountUpdate",
				QueryType:  snapsqlgo.QueryLogQueryTypeExec,
				Options:    queryLogOptions,
			}, executor
		})
		stmt, err := executor.PrepareContext(ctx, query)
		if err != nil {
			err = fmt.Errorf("AccountUpdate: failed to prepare statement: %w (query: %s)", err, query)
			_ = yield(nil, err)
			return
		}
		defer stmt.Close()

		rows, err := stmt.QueryContext(ctx, args...)
		if err != nil {
			err = fmt.Errorf("AccountUpdate: failed to execute query: %w", err)
			_ = yield(nil, err)
			return
		}
		defer rows.Close()

		for rows.Next() {
			item := new(AccountUpdateResult)
			if err := rows.Scan(
				&item.ID,
				&item.Status,
			); err != nil {
				err = fmt.Errorf("AccountUpdate: failed to scan row: %w", err)
				_ = yield(nil, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}

		if err := rows.Err(); err != nil {
			err = fmt.Errorf("AccountUpdate: error iterating rows: %w", err)
			_ = yield(nil, err)
			return
		}
	}
}
